label ch4_main:
    stop music fadeout 2.0
    scene bg residential_day
    with dissolve_scene_full

    play music t6

    "已经到周日了。"
    if ch4_scene == "natsuki":
        "夏树马上就要过来了，我变得越来越焦虑。"
        "我不断地告诉自己别紧张，但是并没有什么效果。"
        "不知道只有我们两个的时候，她会不会变得不一样？"
        "与此同时，她已经给我发了很多条短信了。"
        "交换了手机号后，我们互相发了一条短信来确认，但后来却变成了对话。"
        "她在手机上的性格几乎完全不一样，会用一堆颜文字和可爱的词语。"
        "她也很喜欢抱怨，不过我也已经料到了。"
        "不过先把夏树放到一边......"
    else:
        "优里马上就要过来了，我变得越来越焦虑。"
        "我不断地告诉自己别紧张，但是并没有什么效果。"
        "优里大体上显然是一个内向而又亲切的人。"
        "如果只有我们两个的话，她肯定会更放得更开。"
        "与此同时，我们甚至会偶尔发发短信。"
        "她一开始极为忐忑不安，不过我很快就对她有了更多了解。"
        "不过先把优里放到一边......"
    "自从那天纱世里提前离开社团后，我就再也没有听到她的消息了。"
    "虽然我们其实也不常发短信......"
    "但是我心里一直在暗暗担心。"
    "对比纱世里所说的话，和莫妮卡所说的话......"
    "在纱世里可能需要我时毫不理会她的感受，这么做真的可以吗？"

    stop music fadeout 2.0
    scene bg house
    with wipeleft_scene
    "我决定在[ch4_name]来之前先去纱世里家看看。"
    "我没有开口问，而是和以往一样，直接告诉她‘我要过来一趟’。"
    "到达纱世里家时，我先是敲了敲门，而后自己走了进去。"
    "我们过去常常一起玩，所以养成了像家人一样直接进对方家门的习惯。"
    scene black with wipeleft
    "房子里很安静。"
    "纱世里不在一楼，所以我猜她会在楼上自己的房间里。"
    "她没跑下来欢迎我，已经让我觉得很奇怪了。"
    "我走到她的卧室，终于找到了她。"
    scene bg sayori_bedroom with wipeleft
    mc "纱世里？"
    play music t10
    show sayori 1ba zorder 2 at t11
    s "嗨，[player]~"
    show sayori 1by
    "我在她的房间坐下。"
    "纱世里勉强挤出了一个微笑。但旁人很容易看出来，她有些不太对劲。"
    "我们之间小小地沉默了一会儿。"
    s "你已经好久没这样过来找我了吧？"
    mc "啊......你说得没错。"
    mc "确实已经好久了。"
    mc "其实也没什么变化，对吧？"
    "纱世里的房间和往常一样乱糟糟的。"
    "我也认出了她那多年以来没变过的毛绒玩具和墙饰。"
    s 2bl "欸嘿嘿~"
    s "如果你经常来的话，这里就不会这么乱啦。"
    mc "那是因为最后都是我来帮你打扫了......"
    s 1bb "你怎么今天突然想过来了？"
    s "你今天不是要和[ch4_name]见面吗？"
    mc "是啊，但是......"
    mc "......等一下，你怎么知道的？"
    "上次开会决定这件事的时候，纱世里已经提前走了。"
    s 1ba "是莫妮卡告诉我的。"
    s "她告知我学园祭的准备工作分配，不是很正常吗？"
    mc "啊，也是......"
    mc "但是你呢？"
    mc "你今天不是应该去帮莫妮卡吗？"
    s 4bb "当然帮啦！"
    s "但是我只需要在网上帮她。"
    s "我们没计划要见面什么的。"
    mc "啊，这样的话就只有我和[ch4_name]了......"
    s 1ba "是的~"
    "我们之间又陷入了更长的沉默。"
    show sayori 1bk
    "纱世里的眼神飘忽着。"
    "她现在的行为真的有些反常。"
    "我终于说到了重点。"
    mc "我只是......想看看你怎么样了。"
    mc "自从你周五离开了之后。"
    mc "一定是发生了什么吧，你瞒不住我的！"
    mc "我太了解你了。"
    mc "所以说......"
    "纱世里笑着摇摇头。"
    s 1bd "这可不行啊，[player]。"
    mc "诶？"
    s "为什么就不能像过去一样呢？"
    s 1by "都是我的错。"
    s "如果我没有这么软弱，也没有无意中表达出我的感情......"
    s 1bk "如果我没有犯下那个愚蠢的错误......"
    s "那么你就完全不会担心我了。"
    s "你也不会到这里来。"
    s 1bd "你现在也不会想着我。"
    s "但这......都是我咎由自取，不是吗？"
    s "我正在因为我的自私而受到惩罚。"
    s "我想这也是为什么，上天会让你今天过来。"
    s "它只是想要折磨我。"
    s 4bq "欸嘿嘿~"
    mc "纱世里！"
    show sayori 4bb
    "我抓住了纱世里的肩膀。"
    mc "你到底在说些什么啊？！"
    mc "你到底知道自己在说什么吗？"
    mc "我知道你肯定是遇到什么事了。"
    mc "除此以外，没有别的解释能说明你为什么会变成这样。"
    mc "所以你干脆就告诉我吧......！"
    mc "除非你告诉我，不然我无法停止思考这个问题！"
    s 4bl "啊......"
    s "啊哈哈......"
    "纱世里给了我一个空洞的微笑。"
    s 4by "[player]，你真的让我不知所措了。"
    s "不过......"
    s 1ba "你搞错了。"
    s "我没有‘遇到’什么事。"
    s "我一直都是这样的。"
    s "你只不过是第一次看到而已。"
    mc "看到什么啊？"
    mc "纱世里，你到底在说什么啊？"
    s 1bq "欸嘿嘿~"
    s 1ba "你这是真的想让我说出来了，是吧，[player]？"
    s "我想这次是别无选择了。"
    s 1bc "事实上......"
    s "我的人生一直以来都在严重的抑郁症中度过。"
    s 1bb "你知道吗？"
    s "不然你以为我为什么每天上学都会迟到？"
    s "那是因为每天，我甚至连起床的理由都找不到。"
    s 1by "我都完全清楚自己有多没用了，还有什么理由去做任何事情呢？"
    s "为什么要去学校？"
    s "为什么要吃饭？"
    s "为什么要交朋友？"
    s "为什么要让别人的精力和关心白白浪费在我的身上？"
    s "就是这种感觉。"
    s "而这也是为什么我只想让大家都开开心心......"
    s "而不是让别人来担心我。"
    mc "......"
    "我被震惊到了。"
    "我甚至都不知道该如何回应。"
    "我认识纱世里都这么久了，她是怎么做到把这一面完全藏起来的？"
    "她真的有那么不想让我担心她吗？"
    mc "......为什么啊，纱世里？"
    s 1bg "诶......？"
    mc "为什么你从来都没有告诉过我？"
    mc "作为你的好友，我感觉像是被背叛了。"
    mc "因为如果我知道的话，我一定会竭尽全力帮助你的！"
    mc "即便我能做的并不多......"
    mc "但我还是会更加努力，让你的每一天都变得更好过一点。"
    mc "这不就是我们做朋友的意义吗！"
    mc "你只要告诉我就行了！"
    s 1bk "[player]，你一点都不懂。"
    s "你以为我为什么不告诉你？"
    s 1bd "因为如果我告诉了你，你就会浪费精力来照顾我，而不是去做重要的事情。"
    s "我不想被人关心。"
    s "别人想要关心我时，那种感觉甜蜜又苦涩。"
    s 1ba "有时候会感觉很好。"
    s "但有时候也会感觉像是头上挨了一闷棍。"
    s 4bq "啊哈哈~"
    s 4ba "这也是为什么，我当时如此强烈地希望你和其他人交朋友......"
    s "对我来说，大家快快乐乐在一起，这就是最好的事。"
    s 1bb "但是随后，我又发现了另一件事。"
    s "看着你和社团里的所有人交上朋友、并且变得越来越亲近......"
    s 1bk "我又觉得像是万箭穿心一样。"
    s "所以，这就是原因了。"
    s "这就是为什么我觉得这个世界只想要折磨我。"
    s 1by "每条路的尽头都只有痛苦。"
    s "啊哈哈~"
    mc "你说的对，我确实不明白......"
    mc "我一点也不明白你的感受，纱世里。"
    mc "但是我不需要明白。"
    mc "只要能让你停止受伤，不管要做什么样的事情......"
    mc "我都会去做。"
    s 1bd "你错了，[player]"
    s "什么都没用的。"
    s "你什么都做不了。"
    s "唯一能到帮我的，就是让一切都维持原状。"
    s 1bk "但是我太自私了。"
    s "我最后还是让你看到了，我是多么差劲的一个人。"
    "泪水从纱世里脸上滑落。"
    s 1bv "因为我的自私，我让你加入了文学部。"
    s "于是我受到了心痛的惩罚，我连为什么心痛都搞不清楚。"
    s "而现在你到我家找我，我却害得你也心痛了起来。"
    s 1bt "我可真是软弱而又自私。"
    s "除此之外我什么都不是。"
    s "这也是为什么我要接受这些惩罚。"
    s 1bv "因为这都是我咎由自取......！"
    "我不假思索地又一次抓住了纱世里的肩膀。"
    "这次，我把她紧紧地抱在怀里。"
    scene black with dissolve_cg
    s "啊、啊——"
    s "[player]......"
    mc "纱世里。"
    mc "我不在乎你是否觉得自己自私。"
    mc "对于你能说服我加入社团这件事，我真的很高兴。"
    mc "能够每天看到你，就已经很值得了。"
    mc "如果我能和其他人交朋友，那也只是额外的收获。"
    mc "但请你一定不要低估了我有多么在乎你。"
    mc "这一点我是不会改变的。"
    s "[player]......"
    "纱世里并没有回抱我。"
    "尽管我双臂揽着纱世里，她的手臂却还是垂在两边。"
    "她开始在我耳边抽泣。"
    s "不......"
    s "不要这样......对我......"
    s "求你不要这样......"
    s "[player]......"
    s "我......"
    "纱世里抽泣着，几乎说不出话来。"
    "我不知道自己现在做得对不对。"
    "但我只是想让她知道，我在乎她。"
    mc "如果你下狠心觉得自己自私的话，那么你也要允许我的自私。"
    mc "不管有多艰难，我一定要找出帮助你的办法。"
    mc "你的那种心情，我会帮你打消的。"
    mc "所以，如果你有什么需要我做的的话......"
    mc "那你一定要告诉我。"
    mc "不然我可是会生气的。"
    s "......"
    s "我......不知道......"
    s "我不知道......"
    s "我不知道。"
    "纱世里终于回应了我的拥抱，轻轻搂住了我。"
    s "我什么都不知道。"
    s "真的好可怕......"
    s "[player]，我一点也不明白自己的感受......"
    s "我只有在疼痛时，才不会觉得自己毫无知觉。"
    s "不过......"
    s "你的拥抱好温暖......"
    s "......但也很可怕。"
    scene bg sayori_bedroom
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "纱世里松开了我。"
    "她一松手，我也松开了她。"
    mc "明天就是学园祭了。"
    s 1bk "嗯......"
    mc "会很有趣的，对吧？"
    s "嗯。"
    mc "学园祭那天，你愿意和我一起度过吗？"
    s 1bh "唔、唔......"
    s "啊——"
    mc "我就想陪着你，真心的。"
    mc "不骗你。"
    s 1bk "我......"
    s "那我觉得还不错......"
    mc "嗯。"
    "纱世里抹了抹眼睛。"
    "要是能今天一天都呆在这里，我一定会这么做。"
    mc "但我偏偏在今天有其他安排......"
    mc "要不我去跟她说取消——"
    s 1bh "不，不要——！"
    s 1bg "真的不要......"
    s "如果你取消了......那我绝对不会原谅你的。"
    mc "可是......"
    mc "差不多到[ch4_name]来我家见我的时候了......"
    mc "要不，你愿意过来帮忙吗？"
    mc "一定会很有趣的。"
    "出乎我的意料，纱世里摇了摇头。"
    s 1bd "对不起。"
    s "我不知道今天的我还适不适合这么做。"
    s "你能理解的，对吧？"
    mc "啊......"
    mc "这......对我来说很难完全理解。"
    mc "不过我会尽最大努力理解的。"
    s "没关系。"
    s "不要太担心了。"
    s 4ba "我们明天再见，好吗？"
    mc "......好吧。"
    mc "我很期待哦。"
    scene bg residential_day with wipeleft_scene
    "我对纱世里说了声再见，然后走出了她家。"
    "回家的路上，我发现自己仍然忐忑不安。"
    "但是[ch4_name]快来了，我也不能再多想了......"
    "我觉得纱世里说得对。"
    "我不应该担心太多，我们明天一定会玩得很开心。"
    "我应该把注意力集中在眼前的事情上！"
    call expression "ch4_exclusive_" + ch4_scene
    call ch4_end

    return


label ch4_exclusive_natsuki:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "回到家后，我紧张地等待着夏树的到来，但其实只等了几分钟。"
    "很快，她就发短信说她已经到门口了。"
    "我马上去开了门，让她进来。"
    show natsuki 2bj zorder 2 at t11
    mc "......"
    n "怎么了？"
    mc "......嘿。"
    "我也不知道自己在期待什么，不过夏树穿的竟然不是校服，这真是完全出乎我的意料。"
    "和这么可爱的衣服一比，校服似乎变得完全不适合她了。"
    n 4bc "真是的，不要搞得这么尴尬啊！"
    n "还有一整个下午呢，别搞得这么奇奇怪怪的，不就是没在校外见过我么。"
    n "总之，我要进来了。"
    scene bg kitchen
    show natsuki 1bj zorder 2 at t11
    with wipeleft
    mc "我看你带了很多东西......"
    "夏树拎着一个大袋子，里面大概装满了烘焙用品。"
    n 2bj "嗯，我可不想来了之后才发现你的厨房根本不适合做烘焙。"
    n "我让你买的东西都买齐了吗？"
    mc "嗯，买好了的。"
    "昨天，夏树要求去我买了一大堆家里没有的原料。"
    n 2bl "很好！"
    n "你还算靠得住嘛。"
    mc "那......当然。"
    "我很惊讶夏树会突然这么说，她平常可是挺尖酸刻薄的。"
    "是不是因为她在校外有些不一样呢？"
    mc "好了，我们去厨房吧......"
    n 2by "什么，你都不帮我拎一下这个重得要死的袋子吗？"
    n "[player]，你的待客之道去哪了？"
    mc "拜托......"
    mc "有必要非得让我那么一板一眼地扮成一个绅士吗？"
    "我接过了夏树递给我的袋子。"
    mc "噶——"
    mc "怎么这么沉啊——！"
    n 4bz "啊哈哈！"
    n "我可是一路拎过来的呢。"
    n 4bl "佩服我不？"
    mc "明白了......"
    mc "是啊，我五体投地，夏树。"
    mc "我以前好像小看你了。"
    n 4by "欸嘿嘿~"
    n "是因为我长得太小了吗？"
    n 4ba "你个混蛋。"
    "夏树锤了我胸口一拳。"
    mc "喂喂喂。"
    mc "和你的身材没有关系。"
    mc "你真那么讨厌长得小吗？"
    n 1bk "欸？"
    n "唔......"
    n 1bc "也不算是讨厌......"
    n "只是，有时候人们觉得能力和身材大小成正比，而我想证明他们是错的。"
    n 1ba "我身型娇小，却依旧能比别人更优秀的话，我会很开心的。"
    n "不过......"
    n 5bw "......算了，当我没说！"
    n "你看你害我说了些什么啊？"
    n 5bq "不要觉得因为不在学校，你就可以让我说一些奇奇怪怪的话！"
    n "可以开始了吗，还是说有别的事？我可是有很多东西要教你。"
    mc "啊哈哈。"
    n 5bn "什么啊？？"
    mc "这样才比较像你嘛。"
    mc "还是直接说出自己想法的你更有趣些。"
    n 1bm "喂、喂！"
    n "你现在{i}就是{/i}在把我当小孩对待啊！"
    n "我只是想对你好一点，真的。"
    n 1br "虽然我没有优里那样成熟性感的身材，但那并不代表你就可以那样对——"
    n 1bo "啊、啊——"
    "夏树没继续说下去，脸也变红了。"
    mc "夏树......"
    n 1bp "你给我忘掉！"
    n "我什么都没说！"
    mc "我应该向你道歉。"
    n 1bh "诶？"
    mc "我很感激你说想对我好一些。"
    mc "我也应该多体谅你一点的。"
    mc "不过话说回来......"
    mc "如果你是那么认为的，那么你也应该知道，世界上有很多人喜欢你这样的体型。"
    n 1bq "啊......"
    n "你又是怎么......知道的？"
    mc "这方面你只要相信我就行了。"
    n "......"
    n 5bx "......恶心。"
    mc "喂！"
    mc "你是在说我吗？"
    n 5bw "这里还有别人吗？"
    mc "够了......"
    mc "我们还是赶紧开始吧。"
    n 2bl "啊哈哈！"
    n "在我说你恶心的时候，你说话都没好声气了。"
    n 2bd "我终于找到你的弱点了，[player]！"
    "夏树意味深长地笑了起来。"
    mc "饶了我吧......"
    "如果夏树决定继续羞辱我，我肯定会反击回去的。"
    "不过她似乎已经满意了，开始从袋子里拿东西，于是我们终于可以开始了。"

    scene bg kitchen
    with wipeleft_scene
    "没过多久，整个厨房就乱成了一团。"
    "勺子、脏碗、面粉、洒出的液体和塑料袋散落在每一个台面上。"
    "搅拌器太小，没法一次性做出所有面糊，所以我们只能分好几次来做。"
    "与此同时，夏树还要像照顾小孩一样盯着我，确保我不会糟蹋了她珍贵的点心作品。"
    show natsuki 2bk zorder 2 at t11
    n "[player]，你把食用色素放哪了？"
    n "面糊马上就要进烤箱了，我得赶紧把烤盘装好。"
    mc "我记得它还在桌子边上的袋子里。"
    mc "你要用它干什么？"
    n 4bl "当然是给面糊上色了！"
    n 4bj "我想让每盘面糊的颜色都不一样。"
    n "这样的话，即便味道没什么两样，大家仍然可以挑出自己的最爱。"
    mc "啊，这想法挺可爱的。"
    mc "糖霜也要这么做吗？"
    n 4bk "你想这么做吗？"
    mc "啊......"
    mc "你是在问我吗？"
    mc "我其实没什么偏好，所以......"
    n 1bm "拜托......"
    n "你根本没有用心在做！"
    n "你就不能至少试着找点乐趣吗？"
    mc "我有在找乐趣了啊......"
    "我不太清楚夏树还想要我怎么样。"
    "与此同时，我看她把面糊分到了更小的碗里，然后往每个碗里加了几滴食用色素。"
    mc "啊，看上去不错啊。"
    n 2bj "是吧？"
    n "烘焙可不只是按部就班。"
    n "你可以在外观上发挥创意，而这也是最具乐趣的地方。"
    n "如果光是看到它就能让大家眼前一亮，那就值了成千上万倍。"
    mc "就跟我第一天进社团时你做的那些蛋糕一样，是吗？"
    "我回忆起当时夏树骄傲地展示她的猫咪纸杯蛋糕，以及纱世里和莫妮卡脸上欣喜的表情。"
    "我不知道自己能不能也让夏树那么骄傲。"
    mc "嗯......"
    mc "那我也加一点食用色素吧。"
    n "看来你开窍了嘛。"
    n "在加入食用色素前，记得一定要确保糖霜已经完全搅拌好了。"
    mc "好，马上就好。"
    "我们把电动搅拌机拿来打面糊，所以我只能拿一个搅拌器和一个大碗来搅拌糖霜。"
    n 4bc "诶？"
    n "糖霜里还有好多块状物啊！"
    n "你到底有没有在努力啊？"
    mc "呃，有啊......"
    mc "只不过还需要一点时间而已。"
    n 4bg "真是的，按你这么做的话，我整个晚上都要耗在这了。"
    n "我先来，你看好了。"
    "夏树从我手中夺过搅拌器，并用另一只手将碗倾斜。"
    n 4be "你必须要......用力......狠狠地把它打散！"
    "几秒之后，糖霜的粘稠度已经均匀了不少。"
    n 4ba "你看？"
    "似乎是为了强调，夏树将一根手指伸进糖霜，然后放到了嘴里。"
    "我迟疑地打算照做。"
    n 1bh "喂！"
    "夏树突然抓住了我的手腕。"
    n 4bh "别把{i}你{/i}那恶心的手指伸进我的糖霜里。"
    mc "诶，你的糖霜吗？"
    mc "你是不是忘了力气到底是谁出的啊？"
    "我开始回击，试图一点点地把我的手指伸向碗里。"
    n 4by "别逼我把你揍成一团面糊哦！"
    mc "我倒想看看你敢不敢这么做！"
    "我继续伸长了手，刚好能让我的手指碰到糖霜。"
    "就在夏树用尽全力把我拽开的同时，我得意洋洋地用手刮起了一些糖霜。"
    mc "啊——！"
    "夏树拉得我踉跄了一下，反过来也让她没站稳。"
    n 1bx "恶心！"
    n "你把它弄到我脸上了！"
    mc "那又是谁的错啊？！"
    "夏树的脸颊上有一大团糖霜。"
    n 1bw "嗯——"
    "她试着伸长舌头去舔，但是离得太远了。"
    n 1br "真是的......"
    n "你猜怎么着？"
    n 4bd "吃我这招！"
    "夏树用手指把糖霜擦掉，然后猛地朝我脸上一戳。"
    mc "你倒是想得美——！"
    "我的动作更快。"
    "在她的手指碰到我之前，我先抓住了她的手腕。"
    "夏树试图用另一只手反击，但是同样也被我抓住了。"
    $ persistent.clear[4] = True
    $ renpy.save_persistent()
    scene n_cg3_base
    show n_cg3_exp1
    show n_cg3_cake
    with dissolve_cg
    n "啊哈哈哈！快停下！"
    mc "除非你为说我恶心这件事道歉！"
    n "好吧好吧！"
    n "对不起，我不该说你恶心。"
    n "你知道我不是故意的。"
    n "只是看你这么大反应还挺有意思的。"
    n "......而且你也一直都是那样对我的，是吧！"
    n "说着一些很蠢的话，只是想看看我的反应。"
    n "你不应该那样戏弄女生的。"
    mc "是这样吗？"
    mc "那样的话，我好像不该这么做......"
    show n_cg3_cake at cgfade
    hide n_cg3_cake
    "我抓过夏树的手指并放进了嘴里，舔掉了上面的糖霜。"
    show n_cg3_exp1 at cgfade
    show n_cg3_exp2 at cgfade
    hide n_cg3_exp1
    n "什、什、什么——？"
    n "你、你刚刚不会是真的——"
    n "啊、啊——"
    "夏树惊呆了，连怎么对我生气都不知道了。"
    "她的脸变得通红。"
    hide n_cg3_exp2
    n "[player]......"
    n "你真的不应该对女生做这种事的......除非你真的很喜欢人家......"
    n "你知道的......吧？"
    mc "......"
    "她这样算是在问我什么吗？"
    "气氛怎么一下子变成了这样？"
    mc "我......"
    "夏树安静地看着我。"
    "我注意到了她那浅浅的呼吸。"
    "为什么我开始觉得有点头晕了......？"
    n "诶？！"
    scene bg kitchen with dissolve_cg
    "忽然间，火警警报器毫无征兆地响了起来。"
    "夏树冲向了烤箱。"
    mc "有什么东西烧焦了吗？"
    mc "你不是还没把蛋糕放进去吗？"
    show natsuki 1bw zorder 2 at t11
    n "{i}*咳咳*{/i}"
    n "我就说呢......"
    n 1bb "你忘记收那个脏托盘了，笨蛋！"
    n "你怎么会犯下这样的错误？"
    mc "你在开启烤箱前就应该先检查一下的！"
    n 1bs "不要把你的黑锅甩给我！"
    n "真是的......"
    "夏树戴上隔热手套，把焦黑的托盘从烤箱里拿了出来。"
    "她把它放到了炉子上。"
    "不一会儿，火警警报停了。"
    n 1bq "总之......"
    n "我要......把蛋糕放进烤箱里了。"
    mc "嗯......"
    "前一刻的紧张气氛仍然在我们之间弥漫。"
    "但时机已经错过了。"
    "我看着夏树把装有蛋糕的托盘放入烤箱。"
    "然后，我有些不甘心地拿起搅拌器继续制作糖霜，像是之前什么都没发生一样。"

    scene bg kitchen
    show natsuki 4bz zorder 2 at t11
    with wipeleft_scene
    n "啊，闻起来不错！"
    "蛋糕已经可以从烤箱里拿出来了。"
    "夏树一打开烤箱门，一股香甜温暖的气息便瞬间充满了整个房间。"
    n 4bl "你看它们多可爱呀！"
    "她自豪地向我炫耀每个托盘上颜色各异的纸杯蛋糕。"
    mc "加上糖霜之后会更好看的。"
    n 2ba "这当然不需要你来告诉{i}我{/i}啦！"
    n "我带了裱花工具，希望你能发挥一下创意。"
    n "给，把糖霜铲到袋子里。"
    "夏树给了我几个塑料袋。"
    n 2bj "这些裱花嘴可以让糖霜好看又蓬松。"
    n "这一个还可以做出花来！"
    n "不过这次我们大概不会用到这个。"
    mc "那这个是干嘛用的？"
    "我拿起了一个嘴尖比其它几个要细得多的裱花嘴。"
    n 4bk "这个很细，所以可以用来画线或者别的图案。"
    n "不过也可以用它在蛋糕上写字。"
    n "比如说‘生日快乐！’之类的。"
    mc "嗯，明白了......"
    mc "其实，这让我有了个点子。"
    n "诶？"
    mc "嗯，这是一次文学活动，对吧？"
    mc "我们可以在每个纸杯蛋糕上写不同的词，从而呼应文学这个主题。"
    mc "让大家根据自己喜欢的词来挑选蛋糕，应该会很有意思。"
    n 1bq "唔......"
    mc "嗯？"
    n "我还以为你会说一些很傻的东西......"
    n 1bs "不过这个点子其实......还挺可爱的，所以......"
    mc "啊哈哈。"
    mc "我大概是从你身上得到的灵感。"
    n 5bh "你、你这话是什么意思？"
    n "我不可爱啊！"
    mc "拜托......"
    mc "我们不是在学校，没人在评判你。"
    mc "你这个穿着和举止，就不能怪我觉得你可爱啊。"
    n 5bs "那、那......"
    "夏树的声音轻了下去。"
    n "你也一样......"
    mc "诶？"
    mc "你说什么？"
    n 1bw "没、没什么，我什么都没说！"
    n "我们来上糖霜吧！"
    "夏树加快了速度，给每个袋子都装了一个裱花嘴。"
    n 1bh "还有很多事要做，不能在这浪费时间了！"
    n "看好了，我来教你怎么做。"
    "夏树没有给我任何机会思考之前发生了什么事，迅速地行动了起来。"
    "她教我如何上糖霜后，我们就各自开工了。"

    scene bg kitchen with wipeleft_scene
    "终于做完后，夏树把纸杯蛋糕全部并排摆好，欣赏着我们的成果。"
    show natsuki 4bl zorder 2 at t11
    n "你看它们放在一起多好看啊！"
    mc "嗯，确实很好看，不是吗？"
    n 1bm "唔......我好想吃一个！"
    mc "呃，没理由不让你吃，对吧？"
    mc "吃一个也没什么大不了的。"
    n 1bc "嗯，是啊，但是......"
    n "今晚是我爸做晚饭，所以我要留些胃口。"
    mc "啊哈哈。"
    mc "这一点上，纱世里倒是和你正好相反。"
    mc "如果她在这的话，我们这儿恐怕有十个蛋糕要消失了。"
    mc "然后她还会继续吃晚饭。"
    n 4bg "天哪，这样很不健康啊！"
    n 4bs "况且我爸做饭时，我必须尽可能多吃一点......"
    n 4bq "......呃，算啦！"
    n 4bc "我本来还想着我们会有时间看漫画的，但是我要回家吃晚饭了......"
    mc "啊，这么早？"
    mc "真可惜啊。"
    n 1bg "都怪你做得太慢了！"
    n "你早该好好想一想的。"
    n "这样的机会以后可不太会有了哦。"
    mc "够了......"
    "夏树和往常一样怪罪于我。"
    n 2bk "你明天能把纸杯蛋糕带去学校吧？"
    n "如果你和纱世里可以各自带一点的话，那应该就只用带一趟了。"
    mc "嗯，我会带过去的。"
    mc "而且别担心，我连半个都不会让她吃掉的。"
    n 2ba "啊哈哈。"
    n "我真希望她对我的时候，也能像她对你时那样听话。"
    mc "啊......"
    mc "是啊。"
    show natsuki zorder 1 at thide
    hide natsuki
    "我又回想起了今天早些时候和纱世里的对话。"
    "我觉得好无助。"
    "纱世里确实总是听我的，但是当时的她似乎什么都听不进去。"
    show natsuki 4bl zorder 2 at t11
    n "好了，我已经收拾好了。"
    n "你今天干得不错！"
    mc "你也是。"
    mc "我送你出门......吧。"

    scene bg house with wipeleft_scene
    "就这样，夏树已经准备好要走了。"
    "感觉这个下午转瞬即逝。"
    "除此之外......"
    "我有没有像我预期的那样，抓住机会跟她拉近距离呢？"
    show natsuki 1bh zorder 2 at t11
    n "呃......"
    n "我想我要走了，那么......"
    n 1bq "谢谢你的帮忙......"
    n "明天再见咯。"
    mc "等一下，夏树。"
    n 1bh "诶？"
    mc "你之前说了......不太会有这样的机会。"
    mc "其实根本不是那样的！"
    mc "我今天很开心。"
    mc "就像你之前希望的那样，你让我看到了烘焙是多么有乐趣。"
    mc "不过除此之外......"
    mc "你也可以随时过来的，好吗？"
    mc "如果可以的话，我希望这样的机会能多一些。"
    mc "不管你是想看漫画，还是想去哪里——"
    n 1bm "唔——"
    n "你真的是......那个意思吗？"
    "夏树紧张地看着我，似乎在尽力隐藏自己的表情。"
    mc "是啊。"
    mc "我想多花一些时间跟你在一起。"
    n 1bq "[player]......"
    n "我还以为你只在乎今天的任务......"
    n 1br "唔......"
    n 1bn "很抱歉我今天这么早就要走。"
    n "我其实也不想的！"
    n "如果可以的话......我真的想在这里多待一会儿。"
    n "我和你的感觉一样，所以......"
    stop music fadeout 2.0
    show natsuki 1bi at face with dissolve
    "夏树突然靠近了我。"
    mc "夏树，等一下——"
    "夏树站在离我很近的地方，抬头看着我。"
    "我感觉到她的手指轻轻握着我衬衫的两侧，仿佛是在紧紧抓着我。"
    "她那玫瑰色的脸颊与相映的眼眸，连同微微张开的嘴唇，占据了我的整个视野。"
    "这是怎么回事......？"
    "感受到她那轻柔的呼吸，我开始有些晕眩。"
    n 1bh "我已经有好一段时间......"
    n "都有这种感觉了......"
    n 1bo "——！！"
    show natsuki zorder 2 at t11
    "夏树突然往后一跳。"
    n "纱、纱世里？！"
    mc "诶？！"
    show natsuki zorder 2 at t22
    show sayori 1bl zorder 3 at f21
    s "啊......"
    s "嗨、嗨，[player]......"
    mc "纱世里——！"
    mc "我们刚刚不是在——"
    s 1bq "欸嘿嘿~"
    s "没关系的，[player]。"
    s 1ba "我只是顺路过来打个招呼~"
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 5bq "啊、啊......"
    n "怎么说..."
    n 5bw "你、你应该稍微早点过来的！"
    n "我已经准备回去了，所以......"
    show natsuki zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "呀，真的吗？"
    s "那太可惜了......"
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 2bq "嗯，这个嘛......"
    n "明天还能在学园祭上见面，所以也没关系的。"
    n 2bb "不过记得不要在学园祭开始前偷吃蛋糕哦！"
    n "那么，回见！"
    show natsuki at lhide
    hide natsuki
    "夏树慌慌张张地仓促离开了，而纱世里还在那里挥手告别。"
    return

label ch4_exclusive_yuri:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "快到家时，眼前的一幕让我感到好一阵慌乱。"
    mc "优里——？"
    show yuri 2bq zorder 2 at t11
    y "啊......"
    y "谢天谢地......"
    mc "你来得早了点......"
    mc "抱歉我刚刚不在家！"
    mc "等我很久了吗？"
    y 1bf "没有，我也是刚到。"
    y 1bh "不过没人应门铃让我有些紧张......"
    mc "你可以给我发短信的。"
    mc "要是早知道你已经来了，我就会加快脚步回家，也好让你安心。"
    y 2bv "啊......好像是这样......"
    y "我不知道为什么......没有想到。"
    "这应该是常识才对，不过我打算忽略这点。"
    mc "算了......我们进去吧。"
    mc "我看到你带了很多东西。"
    y 1ba "是的。"
    y "那你买齐我要你买的东西了吗？"
    mc "嗯，大概吧。"
    mc "但愿我没有买错。"
    y "我相信没问题的。"
    scene bg bedroom with wipeleft
    "我把优里带到了我的房间。"
    "她做的第一件事就是好奇地环顾了我的房间，搞得我有些紧张。"
    show yuri 2bm zorder 2 at t11
    y "真干净啊......"
    mc "啊哈哈......"
    mc "我在你来之前打扫了一下，所以......"
    y 2ba "你考虑得真周到呀。"
    mc "啊，不是......"
    mc "要是你来的时候房间一团糟，我会很尴尬的。"
    y 1ba "唔......"
    y "嗯，我也喜欢打扫......"
    y "我会很乐意帮你打扫的。"
    mc "啊——"
    mc "那样就更尴尬了！"
    show yuri 1be
    mc "等会儿，别看那里面——！"
    "在优里正打算拉开桌子抽屉时，我一把抓住了她的手腕。"
    y 3bn "啊、啊......"
    y "抱歉......！"
    y 4bb "我刚刚不知道怎么回事，想也没想就......"
    y "我只是忽然走神了！"
    mc "没事的，没事的......"
    "我松开了优里的手腕。"
    show yuri 1bl
    "她把双手紧紧地放到了腿上，仿佛在确保自己监视好它们。"
    mc "那么，呃......"
    mc "我们是不是应该......开始了？"
    y 2bu "啊......"
    y "是的......"
    y 2bf "唔，我计划好了几件事情，好让你帮忙弄一些......"
    y "装饰品，以及其它可以增加气氛的小玩意。"
    mc "增加气氛......？"
    y 1ba "就是......"
    y "气氛灯效、香薰蜡烛那些......"
    mc "哦，哇。"
    mc "我都不知道你打算做这么多呢。"
    y 1bc "当然要做啦。"
    y "我希望这样能帮忙把听众的思绪带到遥远的彼方。"
    y 1ba "虽然很多人只是因为好奇才会过来看看......"
    y 1bj "还有就是为了......纸杯蛋糕吧，我猜......"
    y 1ba "但我下定决心，要给他们提供一次意犹未尽的体验。"
    mc "那很不错啊。"
    mc "有时候，我会很容易忘记你还是个感情相当丰富的人。"
    y 1bt "啊——"
    y 2bt "丰富......？"
    mc "我觉得这是最好的形容方式。"
    y "这是......坏事吗？"
    mc "不，完全不是。"
    mc "实际上，我就挺喜欢你这一点的。"
    y 3bu "I-Is that so...?"
    y "That makes me feel relieved..."
    y "And kind of happy..."
    mc "Yeah, no need to be so anxious."
    mc "You can relax a little."
    y 3bl "放松啊......"
    y 1bf "I brought some things for relaxation."
    y "I was going to use them during the poetry event..."
    mc "Oh yeah? Like what?"
    y "Let's see..."
    "Yuri rummages through her bag."
    "She pulls out a few candles and a wooden cylinder-shaped object."
    y "I did some shopping on the way here, so I happen to have these in my bag."
    y "I planned to cover the windows in black paper and use the candles to light the room."
    y 1ba "I think that would be amazing, don't you?"
    mc "Yeah, that would be really neat."
    mc "What's that wooden thing, though?"
    y 1bf "Oh, this?"
    y "It's a diffuser for essential oils."
    y "How familiar are you with aromatherapy?"
    mc "Not familiar at all..."
    y 1ba "Ah, is that so?"
    y "It's one of my favorite contributors to a positive atmosphere."
    y "Depending on the oils or herbs you choose, you can change the mood of the air itself."
    y "You can even feel it permeate through your body."
    y 3bm "Relaxation, positive energy, romance, reflection..."
    y "It's almost like magic."
    show yuri 3ba
    "Yuri takes the cylinder and pushes a switch on the bottom."
    "In just a moment, a thin ray of vapor begins to spout through a small hole on the top."
    mc "Wow, that smells wonderful."
    mc "What kind of mood is that one for?"
    y 1ba "This is a Jasmine essential oil."
    y "It smells a little sweet and flowery, right?"
    mc "Yeah, that's a good way to describe it."
    y 1bb "I chose Jasmine for the event because it provides more than relaxation."
    y "Jasmine enhances your emotions and helps you feel them flow through your body."
    y 1bu "You feel warmer, and your heart pounds more heavily."
    y 1ba "Don't you think that will be perfect for sharing our poems?"
    mc "It does sound suitable..."
    mc "But you seem to know a lot about this, so I'll trust your opinion with anything."
    show yuri 1bc
    "Yuri smiles gently, clearly enjoying herself."
    "She again reaches into her bag and pulls out several spools of thin ribbon."
    show yuri 1ba
    mc "What are those for?"
    y 1bf "Well..."
    y "Did you purchase the origami paper I asked you to get?"
    mc "Yeah, I have it over here..."
    y "We won't be using the paper for folding origami."
    y "What I'd like to do is write a different word on each paper."
    y "We'll need about a hundred of them."
    mc "Oh yeah?"
    mc "What will those be used for?"
    y 2bf "Well, I'm going to cut pieces of ribbon to hang from the doorway of the classroom."
    y "Then, we can fasten the paper onto the ribbons to create a doorway curtain."
    y 2bm "Wouldn't that be beautiful?"
    y "It would also catch the eye of those passing by the room..."
    y 2ba "It may attract some to peek inside."
    mc "That's really creative!"
    mc "I had no idea you'd be so good at this, Yuri."
    y 4ba "Is...that so?"
    y "Well, I suppose I do get a little intense...as you'd put it."
    y 3bu "Uhuhu."
    "Yuri giggles with red cheeks."
    "Is it just me, or is she more relaxed when it's just the two of us?"
    "Or maybe it's the excitement she feels from sharing something that she enjoys."
    y 1ba "Here's a marker, [player]."
    y "You can write any characters you want."
    y "I'll help you once I finish cutting the ribbons."
    mc "Ah, alright."
    "Sitting on the floor together, the two of us get to work."
    "I carefully draw a different character on each paper, doing my best to manage my bad handwriting."
    "Yuri unravels a long strand of red ribbon to her desired length."
    "Then, she reaches into her bag once more and pulls out a pocket knife."
    mc "Eh...?"
    "The knife is strangely beautiful."
    "The silver handle has an intricate pattern of waves etched into it."
    "The blade itself is gently tinted blue."
    mc "That's no ordinary pocket knife..."
    mc "It looks really fancy."
    y 4bb "啊、啊......"
    y "Well..."
    "Embarrassed, Yuri looks away."
    mc "What is it?"
    y "You're going to think it's weird..."
    mc "Yuri, whatever it is, I have no reason to judge."
    mc "To each their own, you know?"
    y "If you promise you won't be weirded out..."
    mc "Yeah, I promise."
    y 2bi "Alright..."
    y "The thing is, I'm kind of into knives..."
    y "They're just...so pretty..."
    y 2bv "I-I can't help it!"
    y "I don't know what it is..."
    y "The combination of craftsmanship and feeling of danger, maybe..."
    y 4bb "Uu, what am I saying...?"
    y "Please don't think I'm weird for this..."
    mc "啊哈哈。"
    y "You're laughing at me..."
    mc "No, I'm not laughing at you."
    mc "It's just funny how nervous you got about sharing."
    mc "It's...well, it's an interesting thing to be into, I guess."
    mc "But I think it kind of suits you."
    y 2bt "Suits me...?"
    mc "Yeah... It's kind of intense. Ahaha."
    mc "Besides, it's a really cool-looking knife, I can't deny that."
    y 2bu "It is, isn't it...?"
    "Yuri relaxes her expression once again."
    y 1ba "Would you like to hold it?"
    mc "Sure, I'll check it out."
    "Yuri carefully hands me the knife, with the handle facing me."
    "I take it and turn it around in my hands."
    "It feels heavy, and extremely solid."
    "Where do you even get a knife like this...?"
    "Curious of its sharpness, I feel the point of the knife with my index finger."
    mc "Ow--!"
    y 3bn "[player]——！！"
    y "Why did you do that?!"
    mc "I didn't expect it to be that sharp...!"
    mc "I barely touched it at all."
    y "I-It's my fault!"
    y 3bo "I should have warned you..."
    y "This knife is extremely sharp..."
    y "It can cut through skin like it's paper."
    y 2bv "Oh no..."
    "A small drop of blood trickles down the side of my finger."
    "Yuri takes my hand and gives the wound a closer look."
    y 2bt "啊......"
    "She stares at it and noticeably fidgets."
    mc "If you're squeamish, I'll go wash it off now--"
    mc "A-Ah!"
    "Without warning, Yuri puts my finger in her mouth and licks the wound."
    "I feel her tongue curl around my finger."
    "Startled, I instinctively pull my hand back."
    y "哦、哦......"
    y 3bo "请、请原谅我！"
    y "I wasn't thinking!"
    y 4bc "我......"
    "Yuri lowers her head, her face burning up."
    mc "优里......"
    y "That's the most embarrassing thing I've ever done..."
    y "How could I do something like that??"
    y "I'm sorry, I'm sorry..."
    mc "啊......"
    "Sure, it was a little weird, and it took me by surprise..."
    "But I guess she was just trying to help, right...?"
    mc "Yuri, I think you're overreacting a little..."
    y "唔呃......"
    "She doesn't lift her head."
    "What if she doesn't recover from this for the rest of the afternoon?"
    mc "Alright, you know what..."
    "This might be a stupid thing to do, but I do it anyway."
    "I take Yuri's hand and lick her index finger in return."
    show yuri 3bn at h11
    y "[player]——！！"
    y "D-Did you really just do that?"
    mc "N-Now we're even..."
    y 3bv "......"
    "Yuri just looks at me like I did something wrong."
    mc "啊哈哈......"
    mc "I knew that would be a bad idea..."
    "If not for the sweet aroma of the Jasmine oil, the air would be extremely heavy right now."
    y 1bu "You're so weird, [player]."
    "Yuri giggles shyly."
    mc "诶......？"
    "优里居然说{i}我{/i}奇怪？"
    "我都不知道怎么回应了......"
    y 1bf "Where do you keep your bandages?"
    mc "啊......"
    mc "I don't think I need one, actually."
    mc "It was a tiny cut."
    mc "Look, it already stopped bleeding."
    y 1ba "I see..."
    y "That's relieving."
    "The tension is quickly lifted."
    "We each resume our respective activities."
    "I watch Yuri's knife cut through the ribbon like it's nothing but air."
    "Meanwhile, I continue to make progress on the paper."

    scene bg bedroom with wipeleft_scene
    "After we finish attaching the paper to the ribbons, we lay them all out side by side."
    "It looks better than I expected and will be very effective as a door curtain."
    mc "It looks great."
    mc "Good thinking coming up with this, Yuri."
    show yuri 1bq zorder 2 at t11
    y "Ah, thanks..."
    y "It's just something I saw online, really."
    y 1ba "Are you ready to move onto the next task?"
    mc "Yeah, let's do it."
    mc "What do you have in mind?"
    y "I'd like to create a banner."
    y "That's why I asked you to buy the paint tablets."
    mc "Ah, that's right."
    "One of the items Yuri had asked me to buy was a kit of watercolor paint tablets."
    y 1bf "We'll need about six cups of water to put each of the tablets in."
    y "Do you mind fetching those for us?"
    mc "Of course not."
    mc "Six cups of water..."
    mc "I'll be right back in a minute."
    y 1ba "Thank you very much."
    y 2bf "Oh, and just a little bit of water is okay."
    y "If you fill the cups too much, it will be too diluted."

    scene bg bedroom with wipeleft_scene
    "Taking Yuri's advice, I decide to use small plastic bathroom cups rather than full-sized glasses."
    "I put them on a plate to catch any paint that drips, then bring it back into my room."
    mc "优里？"
    show yuri 1bd zorder 2 at t11
    y "Yes?"
    "I come in to see Yuri quickly unrolling her sleeve, pulling it back over her arm."
    mc "啊，没事......"
    mc "你的脸有点红啊。"
    mc "Is it too hot in here, or anything?"
    y 3bq "啊——"
    y "No, not at all!"
    y "There's nothing wrong, so..."
    y "Let's mix the paint."
    "Yuri hurriedly dismisses me and takes it upon herself to unwrap the tablets, dropping them into the cups."
    y 1ba "So..."
    y "I thought we would do something simple that would look very nice."
    y "I'd like to paint a gradient across the banner..."
    y "Starting with the colors for a sunrise, then daytime, then sunset and nighttime."
    y "Once it dries, I'll write an inspirational quote across the banner."
    y "We can hang it on the wall behind the podium at the front of the classroom."
    mc "Ah, neat."
    mc "What are you going to write?"
    y 2bm "Well..."
    y "...It will be more fun to surprise you."
    "Yuri smiles at me."
    mc "If you say so..."
    show yuri zorder 1 at thide
    hide yuri
    "After rolling out the banner, Yuri and I kneel on opposite sides so we don't get in the way of each other."
    "Yuri uses a brush and adds a few dots of different colors across the banner to serve as a color guide when we paint."
    mc "This kind of reminds me of elementary school..."
    "Painting on a banner with watercolors feels a lot like the art class projects we had back then."
    "It's relaxing."
    show yuri 2bt zorder 2 at t11
    y "啊......"
    y "I'm sorry if this feels too childish...!"
    mc "No, I didn't mean that at all."
    mc "It's kind of fun, you know?"
    y 1bs "...Yeah."
    y "It is fun."
    y "I'm glad you feel that way, too."
    "Yuri stops painting for a moment, thinking to herself."
    y 2bl "For me..."
    y "I don't need to go out and do crazy things to have fun."
    y "In fact, I usually don't even want to."
    y 2bf "I just like when I can spend time with one other person..."
    y "Even if it's something simple, like reading - it doesn't even matter if we don't talk much."
    y 2ba "Just having a friend next to me makes things feel a little bit nicer."
    y "I think that's all it takes for me to be happy."
    mc "Is that so...?"
    "Even if Yuri and I are quite different, I can understand where she's coming from."
    "I feel that way about things like anime and games, where simply sharing the experience with someone can make me happy."
    mc "I think I feel the same way."
    "Yuri smiles gently."
    y 1bm "I knew you'd understand..."
    "Yuri leans over the banner to grab an unused paintbrush."
    "But I move at the same time, causing my head to bump into hers."
    y 3bn "噫呀——！"
    mc "S-Sorry!"
    "Yuri reels back, and I quickly lift my hands in surprise."
    mc "Are you hurt?"
    y 2bv "N-No, I'm not hurt."
    y "It just startled me...that's all."
    y "Sorry, I should have asked you to get it for me..."
    mc "这不是你的错。"
    mc "Ah, your face..."
    "There are droplets of paint on Yuri's face and neck."
    y 2bt "Is there something on my face?"
    mc "Yeah, I accidentally got paint on you..."
    mc "Sorry, it's totally my fault!"
    mc "I'll get a towel right away."
    show yuri zorder 1 at thide
    hide yuri
    "I rush out and fetch a small towel, then I dampen it with hot water."
    "I return to my room and kneel back down in front of her."
    $ persistent.clear[5] = True
    $ renpy.save_persistent()
    scene y_cg3_base with dissolve_cg
    mc "Here..."
    "I pat down Yuri's face and neck with the towel."
    show y_cg3_exp1 at cgfade
    y "啊——"
    mc "Is something wrong?"
    y "It's hot...I just didn't expect it."
    mc "抱歉......"
    mc "我不是很想用冷水。"
    "Having finished, I start to retract my hand."
    "But Yuri suddenly holds my wrist."
    hide y_cg3_exp1
    y "等一下——"
    mc "诶？"
    show y_cg3_exp1 at cgfade
    y "Just...for a little longer."
    y "It feels really nice..."
    mc "啊......"
    "I keep my hand still against Yuri's neck."
    hide y_cg3_exp1
    "She looks into my eyes."
    "It's an intense expression that I recognize from when she reads her books..."
    "Almost as if she's lost in a daze, enveloped by her own thoughts."
    "She breathes gently, half through slightly-parted lips."
    "What is happening...?"
    "Is it the aroma of the Jasmine oil giving me this dizzy feeling?"
    "Yuri's gentle fingers, wrapped around my wrist, send a tingling sensation through my arm."
    "And suddenly, her face seems to be much closer to mine than it was just a moment ago..."
    y "啊......"
    "Yuri slowly pulls away."
    y "抱歉......"
    y "I've been feeling a little light-headed today."
    y "I didn't mean to space out..."
    mc "I-It's fine..."
    scene bedroom with dissolve_cg
    "The moment is over as soon as it began."
    "Yuri picks up her brush again."
    "But her movements seem clumsier, like she's unable to focus."
    "I remain silent, forced to ignore the event that just transpired."
    "I hesitantly retrieve my own brush and continue following Yuri's example."

    scene bedroom with wipeleft_scene
    mc "That should do it..."
    "I finish filling the night sky with white dots that look like stars."
    "Looking at the banner as a whole, it's very pretty and natural-looking."
    show yuri 1ba zorder 2 at t11
    y "I think it came out better than I expected."
    y "I'm really happy with the results."
    mc "Yeah, me too."
    mc "Are you going to add the lettering now?"
    y 1bf "Ah, not yet..."
    y "It needs to dry first."
    mc "That's true, but won't that take a while?"
    y 2bh "Well..."
    y "Perhaps it would be best to leave it here, then have you bring it in the morning."
    y 2bf "I can do the lettering in the classroom before our event starts."
    y "Is that okay?"
    mc "That's totally fine."
    y 1ba "Wonderful."
    y "In that case..."
    y "I don't think there's anything more for us to do here."
    mc "呼。"
    y 1bc "啊哈哈。"
    y "You say that like you're glad it's over."
    y 1ba "Was I wrong to assume that you were at least enjoying yourself a little bit?"
    mc "Ah, no, it's not that."
    mc "I'm just glad that we managed to get everything done."
    y 2ba "I see."
    y "I am, too."
    y "I was a little concerned about time..."
    y "I need to start making dinner soon."
    mc "啊......"
    mc "So you don't have any time left?"
    "I was secretly hoping we would have extra time after finishing the work..."
    y 2bl "那......"
    y "......"
    "Yuri thinks to herself."
    y 3bv "I-I think it would be too irresponsible of me to wait much longer..."
    y "I'm sorry!"
    y "I was hoping there would be more time as well..."
    mc "It's probably my fault."
    mc "Sorry for being such a slow worker."
    y 1bt "No, it's not your fault at all."
    y "And...the important thing is that we got everything done, right?"
    mc "Yeah..."
    y 1bu "So..."
    y "I shouldn't be disappointed...or anything."
    "Gathering all her things, Yuri seems to look a little downcast."
    "I understand why."
    "It sounded like she rarely gets the opportunity to spend time with friends in a relaxed environment."
    "But that doesn't mean this is the last time it can happen..."

    scene bg house with wipeleft_scene
    "Once Yuri packs up, I walk her out the front door."
    show yuri 1ba zorder 2 at t11
    y "Thank you very much for having me today."
    mc "No problem, I'm glad I was able to help."
    mc "Just let me know if there's anything else you need me to bring tomorrow."
    y "I will."
    y 1bu "Well, then..."
    "Yuri fidgets."
    y 2bu "I guess...I'll see you tomorrow."
    mc "等一下——"
    show yuri 2bt
    "I kind of say that without thinking."
    mc "About today..."
    mc "It's fine that we didn't have as much time as we wanted."
    mc "Because we can do this again."
    mc "Whenever you want, you can come over, or we can go out somewhere--"
    mc "Ah, I forgot you don't like going out much--"
    show yuri 2bs
    "As I stumble over my words, Yuri simply smiles bashfully."
    mc "Anyway..."
    mc "You know what I'm trying to say, so..."
    y 1bs "[player]，你真体贴。"
    "优里朝我靠近了一步，然后轻轻地捏了一把我的手。"
    show yuri 2bs at face(y=600) with dissolve
    stop music fadeout 2.0
    y "我还蛮喜欢你这一点的......"
    mc "这个嘛......"
    "这要我怎么回应啊？"
    "不过还没等我回应，优里就突然抽身退了回去。"
    show yuri 3bn zorder 2 at t11
    y "纱、纱世里——？"
    mc "诶？！"
    show sayori 1bl zorder 3 at f21
    show yuri zorder 2 at t22
    s "啊......"
    s "嗨、嗨，[player]......"
    mc "纱世里——！"
    mc "我们刚刚不是在——"
    s 1bq "欸嘿嘿~"
    s "没关系的，[player]。"
    s 1ba "我只是顺路过来打个招呼~"
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 3bq "唔、唔......"
    y "Well, it's nice to see you..."
    y 3bv "I'm sorry, but I'm already on my way to leave!"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "呀，真的吗？"
    s "那太可惜了......"
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 2bt "抱歉......"
    y "不过明天大家都会去学园祭的，所以......"
    y "所以也没关系的，对吧？"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 4bq "那当然！"
    "纱世里笑容满面地说道。"
    show sayori 4ba
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 4bc "是、是啊，那......"
    y "那明天再见！"
    show yuri at lhide
    hide yuri
    "优里显然有些尴尬，匆匆忙忙地走了。"
    "纱世里还在她身后挥手告别。"
    return



label ch4_end:
    play music t10 fadeout 2.0
    show sayori 1ba zorder 2 at t11
    mc "纱世里——"
    mc "我还以为你今天不想过来呢！"
    s 2bl "啊哈哈，好吧......"
    s "我试着呆在房间里......"
    s "但是我的妄想一直折磨着我......"
    s 1by "所以我只好过来亲自看看。"
    mc "看什么啊？"
    mc "你到底在说些什么呀？"
    s "就是......"
    s "来看看你和[ch4_name]玩得有多开心。"
    s "还有你跟她变得有多亲密。"
    s 1bt "我......很高兴......"
    s "你们已经变成了这么好的朋友。"
    s "这对我来说才是最重要的。"
    "泪水开始从纱世里的脸上流下了。"
    s 4bv "这对我来说才是最重要的——！"
    s "[player]，为什么我会有这种感觉？"
    s "我本该为你高兴。"
    s 4bw "为什么我的心却感觉仿佛撕成了两半？"
    s "好疼啊......"
    s "这一切都好疼啊......"
    s "要是我能干脆消失的话，一切都会好很多！"
    mc "纱世里，别那么说！"
    s 1bw "这是事实，[player]！"
    s "要是我不在这个世上，你也就不需要在我的身上浪费你的同情心了！"
    s "你就不需要忍受我的自私！"
    s 1bv "莫妮卡说得没错......"
    s "我就应该直接......"
    mc "莫妮卡......？"
    mc "莫妮卡说的什么没错？"
    s "......"
    mc "纱世里......"
    mc "我之前说的话绝无半句谎言。"
    mc "我不会让你继续像这样痛苦下去的。"
    mc "我对你的关心并不像你想的那样，是一种累赘什么的。"
    mc "对我而言，这不是累赘，而是能让我快乐的事情，"
    mc "是我不会用任何东西来交换的事情。"
    mc "所以，即便必须花上一辈子......"
    mc "我也会一直陪在你身边，直到你再也感受不到痛苦为止。"
    s 1bk "但、但是......"
    "紗世里掉转了目光。"
    "我把手放到她的肩膀上，让她放心。"
    s "我好害怕，[player]......"
    s "我真的很害怕......"
    mc "你在害怕什么，纱世里？"
    s "我害怕......"
    s "比起你喜欢我，我更喜欢你......"
    mc "纱世里......？"
    s 1bu "这是事实，对吧？"
    s "我很软弱，所以就开始过分喜欢你......"
    s "一切都是我作茧自缚。"
    s "[player]......"
    s 4bw "我好喜欢你，喜欢到想要去死！"
    s "这就是我的感受！"
    s 2bv "还有......还有......"
    mc "够了，纱世里......"
    mc "我不想再让你受伤了。"
    "我的手沿着纱世里的手臂往下滑，轻轻地将她的手捏在自己掌中。"
    mc "你还记得我是怎么说的吗，我总是知道什么对你来说才是最好的？"
    mc "你还相信我吗？"
    "纱世里默默地点了点头。"
    mc "即便你不能理解自己的所有情感......"
    mc "我也知道你现在最需要的是什么。"
    mc "而这就是我会给你的答案。"
    show black zorder 4 with dissolve_cg

    menu:
        mc "纱世里......"
        "我爱你。":

            $ sayori_confess = True
            hide black with dissolve_cg
            call ch4_end_yes
        "你永远是我最亲爱的朋友。":
            $ sayori_confess = False
            hide black with dissolve_cg
            call ch4_end_no

    return

label ch4_end_yes:
    mc "我爱你。"
    s 1bv "诶——？"
    mc "这是我的真实感受。"
    mc "所以......你喜欢我的程度，不可能比我喜欢你的程度还多。"
    mc "我真该早点发现的。"
    mc "但是在社团里和大家一起度过的时光......"
    mc "交新朋友......"
    mc "以及每天都和你一起快快乐乐的......"
    mc "这些都让我明白，你才是我最重要的人。"
    mc "这就是为什么我会接受你所背负的一切。"
    mc "只要我们每天像这样继续下去......"
    mc "有你好好陪在我身边......"
    mc "那我们一定都会快快乐乐的。"
    s "[player]......"
    $ persistent.clear[8] = True
    $ renpy.save_persistent()
    scene s_cg3 with dissolve_cg
    "突然之间，纱世里紧紧地抱住了我。"
    s "[player]......"
    s "这样......真的可以吗？"
    mc "嗯。"
    "我把纱世里抱在怀里，又把她抱得更紧了一些。"
    mc "你再也不用放手让我离开了。"
    s "[player]，我爱你......"
    s "我想和你永远在一起。"
    mc "我也是。"
    s "......"
    "我感觉到纱世里抱着我的力量减弱了一些。"
    s "这是怎么回事......？"
    mc "纱世里......？"
    s "我现在应该感到开心啊......"
    s "我一直以为这应该是我最开心的时刻。"
    s "但是为什么啊......？"
    s "即便是现在这种时候......"
    s "为什么乌云还是没有消散啊？"
    s "它们一点也没有消散啊，[player]......"
    mc "没关系的，纱世里......"
    mc "也许要花上一些时间，才能让一切再次好转。"
    mc "不过不管要花多少时间，我都会一路陪着你。"
    mc "这才是当下最重要的事情。"
    s "好、好吧......"
    s "我......相信你......"
    scene bg house
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "纱世里和我慢慢地松开了对方。"
    mc "那么......"
    mc "这样一来，明天的学园祭就是......我们的第一次约会了，是吗？"
    s 1by "欸嘿嘿......"
    s "你在说什么啊？"
    s "我不想去考虑那样的事情，好吗？"
    s "我希望一切都和平常一样。"
    s "即便我们真的......成为了恋人。"
    s 1bk "我不知道自己现在还能不能承受得了更多的事情了......"
    s "对我来说，这一切非常新鲜，但又很可怕。"
    mc "我能理解。"
    mc "我们就按照最适合你的节奏来吧。"
    s 1bd "嘿，[player]......"
    "纱世里又一次看着我，悲伤地微笑着。"
    s 4bd "就算我变得非常、非常伤心......"
    s "这对我来说也是最好的安排......是吗？"
    mc "诶......？"
    "我不是很能理解纱世里说这句话的含义。"
    mc "你是说刚刚发生的一切让你觉得伤心了吗，纱世里？"
    s 4bk "我、我不知道......"
    s "我无法理解自己现在的感受。"
    s "你说你爱我的时候，感觉像是一丛荆棘一样......"
    s 4bd "不过这也是为什么我想要相信你。"
    s "因为，你知道怎么做对我来说才是最好的......"
    mc "......嗯。"
    mc "我知道的。"
    mc "这是我的承诺。"
    show sayori zorder 1 at thide
    hide sayori
    "我嘴上是这么说的，但老实说，纱世里从未像现在这样让我捉摸不透。"
    "我知道我爱她，她也爱我。"
    "但是我也和纱世里一样，没法理解她的感受到底从何而来。"
    "即便我可以安慰她......"
    "我不停想着，我是不是应该做得更多一点，又或者换个别的办法。"
    "我知道在一切回归正轨之前，这些想法还会继续困扰着我。"
    "纱世里之前说不想要任何事物改变，就是这个意思吗？"
    "我不知道。"
    "但是我知道我愿意付出一切。"
    "纱世里是对我最重要的人。"
    "只要能和她有个开心幸福的未来，我什么都愿意做。"
    return


label ch4_end_no:
    mc "你永远是我最亲爱的朋友。"
    mc "你最需要做的，就是让一切保持原样。"
    mc "莫妮卡把实情都跟我说了......"
    mc "她告诉我，你在我加入社团后变得开心了许多。"
    mc "我知道你现在正在和你的负面情绪艰难搏斗。"
    mc "不过......"
    mc "请相信我，我知道对你来说，怎么做才是最好的......该做什么才能让你变得快乐起来。"
    mc "我保证我会让一切都重回正轨。"
    s 1bt "我......"
    s "我......知道了......"
    "纱世里在无比痛苦的表情之中挤出一个微笑。"
    s "啊哈哈......"
    s "胸口被扎了一刀......原来就是这样的感觉吗？"
    s "我真应该为此写一首诗......"
    mc "纱世里——"
    s "没关系的。"
    s "这只不过是我的惩罚......记得吗？"
    s "只不过是在惩罚我的自私......"
    s "所以请你......"
    s "请你不要为这些愚蠢的情感而担心。"
    s "我知道你是对的。"
    s "我一直都知道这样下去是不会有快乐的。"
    s "这就是为什么我会来这里......"
    s "我只是为了得到我需要亲耳听到的答案。"
    s "还有另一件事......"
    s "你说得没错，我只是想让一切重回正轨。"
    s "我现在意识到了。"
    s "[player]，你确实比任何人都要了解我。"
    s 4bv "我什么都相信你......"
    s "任何事情都可以......"
    s "所以......"
    show sayori zorder 1 at thide
    hide sayori
    "纱世里的微笑终于撑不住了。"
    "突然之间，她转身跪倒在地上。"
    s "{i}呜啊啊啊啊啊啊啊啊啊啊——————！！！！{/i}"
    "她双手捂住头，用尽全身力气，大声地尖叫起来。"
    "我被震惊到不知该作何反应。"
    show sayori 4bt zorder 2 at t11
    s "......"
    show sayori at lhide
    hide sayori
    "纱世里扭过头，迅速向我抛出一个更加虚弱的微笑，然后就转身跑了。"
    mc "纱世里！"
    "......"
    "我无助地站在家门口。"
    "为什么我对此感到无比难受？"
    "我什么都做不了。"
    "我能做的最多就是支持纱世里克服她的感受，帮助她重回正轨。"
    "但是我也和纱世里一样，没法理解她的感受到底从何而来。"
    "即便我可以安慰她......"
    "我不停想着，我是不是应该做得更多一点，又或者换个别的办法。"
    "我知道在一切回归正轨之前，这些想法还会继续困扰着我。"
    "我会尽我所能的。"
    "纱世里永远是我最亲爱的朋友。"
    "只要能让她每天绽放微笑，我什么都愿意做。"

    return

