label ch4_main:
    stop music fadeout 2.0
    scene bg residential_day
    with dissolve_scene_full

    play music t6

    "已经到周日了。"
    if ch4_scene == "natsuki":
        "夏树马上就要过来了，我变得越来越焦虑。"
        "我不断地告诉自己别紧张，但是并没有什么效果。"
        "不知道只有我们两个的时候，她会不会变得不一样？"
        "与此同时，她已经给我发了很多条短信了。"
        "交换了手机号后，我们互相发了一条短信来确认，但后来却变成了对话。"
        "她在手机上的性格几乎完全不一样，会用一堆颜文字和可爱的词语。"
        "她也很喜欢抱怨，不过我也已经料到了。"
        "不过先把夏树放到一边......"
    else:
        "优里马上就要过来了，我变得越来越焦虑。"
        "我不断地告诉自己别紧张，但是并没有什么效果。"
        "优里大体上显然是一个内向而又亲切的人。"
        "如果只有我们两个的话，她肯定会更放得更开。"
        "与此同时，我们甚至会偶尔发发短信。"
        "她一开始极为忐忑不安，不过我很快就对她有了更多了解。"
        "不过先把优里放到一边......"
    "自从那天纱世里提前离开社团后，我就再也没有听到她的消息了。"
    "虽然我们其实也不常发短信......"
    "但是我心里一直在暗暗担心。"
    "对比纱世里所说的话，和莫妮卡所说的话......"
    "在纱世里可能需要我时毫不理会她的感受，这么做真的可以吗？"

    stop music fadeout 2.0
    scene bg house
    with wipeleft_scene
    "我决定在[ch4_name]来之前先去纱世里家看看。"
    "我没有开口问，而是和以往一样，直接告诉她‘我要过来一趟’。"
    "到达纱世里家时，我先是敲了敲门，而后自己走了进去。"
    "我们过去常常一起玩，所以养成了像家人一样直接进对方家门的习惯。"
    scene black with wipeleft
    "房子里很安静。"
    "纱世里不在一楼，所以我猜她会在楼上自己的房间里。"
    "她没跑下来欢迎我，已经让我觉得很奇怪了。"
    "我走到她的卧室，终于找到了她。"
    scene bg sayori_bedroom with wipeleft
    mc "纱世里？"
    play music t10
    show sayori 1ba zorder 2 at t11
    s "嗨，[player]~"
    show sayori 1by
    "我在她的房间坐下。"
    "纱世里勉强挤出了一个微笑。但旁人很容易看出来，她有些不太对劲。"
    "我们之间小小地沉默了一会儿。"
    s "你已经好久没这样过来找我了吧？"
    mc "啊......你说得没错。"
    mc "确实已经好久了。"
    mc "其实也没什么变化，对吧？"
    "纱世里的房间和往常一样乱糟糟的。"
    "我也认出了她那多年以来没变过的毛绒玩具和墙饰。"
    s 2bl "欸嘿嘿~"
    s "如果你经常来的话，这里就不会这么乱啦。"
    mc "那是因为最后都是我来帮你打扫了......"
    s 1bb "你怎么今天突然想过来了？"
    s "你今天不是要和[ch4_name]见面吗？"
    mc "是啊，但是......"
    mc "......等一下，你怎么知道的？"
    "上次开会决定这件事的时候，纱世里已经提前走了。"
    s 1ba "是莫妮卡告诉我的。"
    s "她告知我学园祭的准备工作分配，不是很正常吗？"
    mc "啊，也是......"
    mc "但是你呢？"
    mc "你今天不是应该去帮莫妮卡吗？"
    s 4bb "当然帮啦！"
    s "但是我只需要在网上帮她。"
    s "我们没计划要见面什么的。"
    mc "啊，这样的话就只有我和[ch4_name]了......"
    s 1ba "是的~"
    "我们之间又陷入了更长的沉默。"
    show sayori 1bk
    "纱世里的眼神飘忽着。"
    "她现在的行为真的有些反常。"
    "我终于说到了重点。"
    mc "我只是......想看看你怎么样了。"
    mc "自从你周五离开了之后。"
    mc "一定是发生了什么吧，你瞒不住我的！"
    mc "我太了解你了。"
    mc "所以说......"
    "纱世里笑着摇摇头。"
    s 1bd "这可不行啊，[player]。"
    mc "诶？"
    s "为什么就不能像过去一样呢？"
    s 1by "都是我的错。"
    s "如果我没有这么软弱，也没有无意中表达出我的感情......"
    s 1bk "如果我没有犯下那个愚蠢的错误......"
    s "那么你就完全不会担心我了。"
    s "你也不会到这里来。"
    s 1bd "你现在也不会想着我。"
    s "但这......都是我咎由自取，不是吗？"
    s "我正在因为我的自私而受到惩罚。"
    s "我想这也是为什么，上天会让你今天过来。"
    s "它只是想要折磨我。"
    s 4bq "欸嘿嘿~"
    mc "纱世里！"
    show sayori 4bb
    "我抓住了纱世里的肩膀。"
    mc "你到底在说些什么啊？！"
    mc "你到底知道自己在说什么吗？"
    mc "我知道你肯定是遇到什么事了。"
    mc "除此以外，没有别的解释能说明你为什么会变成这样。"
    mc "所以你干脆就告诉我吧......！"
    mc "除非你告诉我，不然我无法停止思考这个问题！"
    s 4bl "啊......"
    s "啊哈哈......"
    "纱世里给了我一个空洞的微笑。"
    s 4by "[player]，你真的让我不知所措了。"
    s "不过......"
    s 1ba "你搞错了。"
    s "我没有‘遇到’什么事。"
    s "我一直都是这样的。"
    s "你只不过是第一次看到而已。"
    mc "看到什么啊？"
    mc "纱世里，你到底在说什么啊？"
    s 1bq "欸嘿嘿~"
    s 1ba "你这是真的想让我说出来了，是吧，[player]？"
    s "我想这次是别无选择了。"
    s 1bc "事实上......"
    s "我的人生一直以来都在严重的抑郁症中度过。"
    s 1bb "你知道吗？"
    s "不然你以为我为什么每天上学都会迟到？"
    s "那是因为每天，我甚至连起床的理由都找不到。"
    s 1by "我都完全清楚自己有多没用了，还有什么理由去做任何事情呢？"
    s "为什么要去学校？"
    s "为什么要吃饭？"
    s "为什么要交朋友？"
    s "为什么要让别人的精力和关心白白浪费在我的身上？"
    s "就是这种感觉。"
    s "而这也是为什么我只想让大家都开开心心......"
    s "而不是让别人来担心我。"
    mc "......"
    "我被震惊到了。"
    "我甚至都不知道该如何回应。"
    "我认识纱世里都这么久了，她是怎么做到把这一面完全藏起来的？"
    "她真的有那么不想让我担心她吗？"
    mc "......为什么啊，纱世里？"
    s 1bg "诶......？"
    mc "为什么你从来都没有告诉过我？"
    mc "作为你的好友，我感觉像是被背叛了。"
    mc "因为如果我知道的话，我一定会竭尽全力帮助你的！"
    mc "即便我能做的并不多......"
    mc "但我还是会更加努力，让你的每一天都变得更好过一点。"
    mc "这不就是我们做朋友的意义吗！"
    mc "你只要告诉我就行了！"
    s 1bk "[player]，你一点都不懂。"
    s "你以为我为什么不告诉你？"
    s 1bd "因为如果我告诉了你，你就会浪费精力来照顾我，而不是去做重要的事情。"
    s "我不想被人关心。"
    s "别人想要关心我时，那种感觉甜蜜又苦涩。"
    s 1ba "有时候会感觉很好。"
    s "但有时候也会感觉像是头上挨了一闷棍。"
    s 4bq "啊哈哈~"
    s 4ba "这也是为什么，我当时如此强烈地希望你和其他人交朋友......"
    s "对我来说，大家快快乐乐在一起，这就是最好的事。"
    s 1bb "但是随后，我又发现了另一件事。"
    s "看着你和社团里的所有人交上朋友、并且变得越来越亲近......"
    s 1bk "我又觉得像是万箭穿心一样。"
    s "所以，这就是原因了。"
    s "这就是为什么我觉得这个世界只想要折磨我。"
    s 1by "每条路的尽头都只有痛苦。"
    s "啊哈哈~"
    mc "你说的对，我确实不明白......"
    mc "我一点也不明白你的感受，纱世里。"
    mc "但是我不需要明白。"
    mc "只要能让你停止受伤，不管要做什么样的事情......"
    mc "我都会去做。"
    s 1bd "你错了，[player]"
    s "什么都没用的。"
    s "你什么都做不了。"
    s "唯一能到帮我的，就是让一切都维持原状。"
    s 1bk "但是我太自私了。"
    s "我最后还是让你看到了，我是多么差劲的一个人。"
    "泪水从纱世里脸上滑落。"
    s 1bv "因为我的自私，我让你加入了文学部。"
    s "于是我受到了心痛的惩罚，我连为什么心痛都搞不清楚。"
    s "而现在你到我家找我，我却害得你也心痛了起来。"
    s 1bt "我可真是软弱而又自私。"
    s "除此之外我什么都不是。"
    s "这也是为什么我要接受这些惩罚。"
    s 1bv "因为这都是我咎由自取......！"
    "我不假思索地又一次抓住了纱世里的肩膀。"
    "这次，我把她紧紧地抱在怀里。"
    scene black with dissolve_cg
    s "啊、啊——"
    s "[player]......"
    mc "纱世里。"
    mc "我不在乎你是否觉得自己自私。"
    mc "对于你能说服我加入社团这件事，我真的很高兴。"
    mc "能够每天看到你，就已经很值得了。"
    mc "如果我能和其他人交朋友，那也只是额外的收获。"
    mc "但请你一定不要低估了我有多么在乎你。"
    mc "这一点我是不会改变的。"
    s "[player]......"
    "纱世里并没有回抱我。"
    "尽管我双臂揽着纱世里，她的手臂却还是垂在两边。"
    "她开始在我耳边抽泣。"
    s "不......"
    s "不要这样......对我......"
    s "求你不要这样......"
    s "[player]......"
    s "我......"
    "纱世里抽泣着，几乎说不出话来。"
    "我不知道自己现在做得对不对。"
    "但我只是想让她知道，我在乎她。"
    mc "如果你下狠心觉得自己自私的话，那么你也要允许我的自私。"
    mc "不管有多艰难，我一定要找出帮助你的办法。"
    mc "你的那种心情，我会帮你打消的。"
    mc "所以，如果你有什么需要我做的的话......"
    mc "那你一定要告诉我。"
    mc "不然我可是会生气的。"
    s "......"
    s "我......不知道......"
    s "我不知道......"
    s "我不知道。"
    "纱世里终于回应了我的拥抱，轻轻搂住了我。"
    s "我什么都不知道。"
    s "真的好可怕......"
    s "[player]，我一点也不明白自己的感受......"
    s "我只有在疼痛时，才不会觉得自己毫无知觉。"
    s "不过......"
    s "你的拥抱好温暖......"
    s "......但也很可怕。"
    scene bg sayori_bedroom
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "纱世里松开了我。"
    "她一松手，我也松开了她。"
    mc "明天就是学园祭了。"
    s 1bk "嗯......"
    mc "会很有趣的，对吧？"
    s "嗯。"
    mc "学园祭那天，你愿意和我一起度过吗？"
    s 1bh "唔、唔......"
    s "啊——"
    mc "我就想陪着你，真心的。"
    mc "不骗你。"
    s 1bk "我......"
    s "那我觉得还不错......"
    mc "嗯。"
    "纱世里抹了抹眼睛。"
    "要是能今天一天都呆在这里，我一定会这么做。"
    mc "但我偏偏在今天有其他安排......"
    mc "要不我去跟她说取消——"
    s 1bh "不，不要——！"
    s 1bg "真的不要......"
    s "如果你取消了......那我绝对不会原谅你的。"
    mc "可是......"
    mc "差不多到[ch4_name]来我家见我的时候了......"
    mc "要不，你愿意过来帮忙吗？"
    mc "一定会很有趣的。"
    "出乎我的意料，纱世里摇了摇头。"
    s 1bd "对不起。"
    s "我不知道今天的我还适不适合这么做。"
    s "你能理解的，对吧？"
    mc "啊......"
    mc "这......对我来说很难完全理解。"
    mc "不过我会尽最大努力理解的。"
    s "没关系。"
    s "不要太担心了。"
    s 4ba "我们明天再见，好吗？"
    mc "......好吧。"
    mc "我很期待哦。"
    scene bg residential_day with wipeleft_scene
    "我对纱世里说了声再见，然后走出了她家。"
    "回家的路上，我发现自己仍然忐忑不安。"
    "但是[ch4_name]快来了，我也不能再多想了......"
    "我觉得纱世里说得对。"
    "我不应该担心太多，我们明天一定会玩得很开心。"
    "我应该把注意力集中在眼前的事情上！"
    call expression "ch4_exclusive_" + ch4_scene
    call ch4_end

    return


label ch4_exclusive_natsuki:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "回到家后，我紧张地等待着夏树的到来，但其实只等了几分钟。"
    "很快，她就发短信说她已经到门口了。"
    "我马上去开了门，让她进来。"
    show natsuki 2bj zorder 2 at t11
    mc "......"
    n "怎么了？"
    mc "......嘿。"
    "我也不知道自己在期待什么，不过夏树穿的竟然不是校服，这真是完全出乎我的意料。"
    "和这么可爱的衣服一比，校服似乎变得完全不适合她了。"
    n 4bc "真是的，不要搞得这么尴尬啊！"
    n "还有一整个下午呢，别搞得这么奇奇怪怪的，不就是没在校外见过我么。"
    n "总之，我要进来了。"
    scene bg kitchen
    show natsuki 1bj zorder 2 at t11
    with wipeleft
    mc "我看你带了很多东西......"
    "夏树拎着一个大袋子，里面大概装满了烘焙用品。"
    n 2bj "嗯，我可不想来了之后才发现你的厨房根本不适合做烘焙。"
    n "我让你买的东西都买齐了吗？"
    mc "嗯，买好了的。"
    "昨天，夏树要求去我买了一大堆家里没有的原料。"
    n 2bl "很好！"
    n "你还算靠得住嘛。"
    mc "那......当然。"
    "我很惊讶夏树会突然这么说，她平常可是挺尖酸刻薄的。"
    "是不是因为她在校外有些不一样呢？"
    mc "好了，我们去厨房吧......"
    n 2by "什么，你都不帮我拎一下这个重得要死的袋子吗？"
    n "[player]，你的待客之道去哪了？"
    mc "拜托......"
    mc "有必要非得让我那么一板一眼地扮成一个绅士吗？"
    "我接过了夏树递给我的袋子。"
    mc "噶——"
    mc "怎么这么沉啊——！"
    n 4bz "啊哈哈！"
    n "我可是一路拎过来的呢。"
    n 4bl "佩服我不？"
    mc "明白了......"
    mc "是啊，我五体投地，夏树。"
    mc "我以前好像小看你了。"
    n 4by "欸嘿嘿~"
    n "是因为我长得太小了吗？"
    n 4ba "你个混蛋。"
    "夏树锤了我胸口一拳。"
    mc "喂喂喂。"
    mc "和你的身材没有关系。"
    mc "你真那么讨厌长得小吗？"
    n 1bk "欸？"
    n "唔......"
    n 1bc "也不算是讨厌......"
    n "只是，有时候人们觉得能力和身材大小成正比，而我想证明他们是错的。"
    n 1ba "我身型娇小，却依旧能比别人更优秀的话，我会很开心的。"
    n "不过......"
    n 5bw "......算了，当我没说！"
    n "你看你害我说了些什么啊？"
    n 5bq "不要觉得因为不在学校，你就可以让我说一些奇奇怪怪的话！"
    n "可以开始了吗，还是说有别的事？我可是有很多东西要教你。"
    mc "啊哈哈。"
    n 5bn "什么啊？？"
    mc "这样才比较像你嘛。"
    mc "还是直接说出自己想法的你更有趣些。"
    n 1bm "喂、喂！"
    n "你现在{i}就是{/i}在把我当小孩对待啊！"
    n "我只是想对你好一点，真的。"
    n 1br "虽然我没有优里那样成熟性感的身材，但那并不代表你就可以那样对——"
    n 1bo "啊、啊——"
    "夏树没继续说下去，脸也变红了。"
    mc "夏树......"
    n 1bp "你给我忘掉！"
    n "我什么都没说！"
    mc "我应该向你道歉。"
    n 1bh "诶？"
    mc "我很感激你说想对我好一些。"
    mc "我也应该多体谅你一点的。"
    mc "不过话说回来......"
    mc "如果你是那么认为的，那么你也应该知道，世界上有很多人喜欢你这样的体型。"
    n 1bq "啊......"
    n "你又是怎么......知道的？"
    mc "这方面你只要相信我就行了。"
    n "......"
    n 5bx "......恶心。"
    mc "喂！"
    mc "你是在说我吗？"
    n 5bw "这里还有别人吗？"
    mc "够了......"
    mc "我们还是赶紧开始吧。"
    n 2bl "啊哈哈！"
    n "在我说你恶心的时候，你说话都没好声气了。"
    n 2bd "我终于找到你的弱点了，[player]！"
    "夏树意味深长地笑了起来。"
    mc "饶了我吧......"
    "如果夏树决定继续羞辱我，我肯定会反击回去的。"
    "不过她似乎已经满意了，开始从袋子里拿东西，于是我们终于可以开始了。"

    scene bg kitchen
    with wipeleft_scene
    "没过多久，整个厨房就乱成了一团。"
    "勺子、脏碗、面粉、洒出的液体和塑料袋散落在每一个台面上。"
    "搅拌器太小，没法一次性做出所有面糊，所以我们只能分好几次来做。"
    "与此同时，夏树还要像照顾小孩一样盯着我，确保我不会糟蹋了她珍贵的点心作品。"
    show natsuki 2bk zorder 2 at t11
    n "[player]，你把食用色素放哪了？"
    n "面糊马上就要进烤箱了，我得赶紧把烤盘装好。"
    mc "我记得它还在桌子边上的袋子里。"
    mc "你要用它干什么？"
    n 4bl "当然是给面糊上色了！"
    n 4bj "我想让每盘面糊的颜色都不一样。"
    n "这样的话，即便味道没什么两样，大家仍然可以挑出自己的最爱。"
    mc "啊，这想法挺可爱的。"
    mc "糖霜也要这么做吗？"
    n 4bk "你想这么做吗？"
    mc "啊......"
    mc "你是在问我吗？"
    mc "我其实没什么偏好，所以......"
    n 1bm "拜托......"
    n "你根本没有用心在做！"
    n "你就不能至少试着找点乐趣吗？"
    mc "我有在找乐趣了啊......"
    "我不太清楚夏树还想要我怎么样。"
    "与此同时，我看她把面糊分到了更小的碗里，然后往每个碗里加了几滴食用色素。"
    mc "啊，看上去不错啊。"
    n 2bj "是吧？"
    n "烘焙可不只是按部就班。"
    n "你可以在外观上发挥创意，而这也是最具乐趣的地方。"
    n "It's a million times more worth it in the end if just looking at it makes everyone's eyes lighten up."
    mc "Like the ones you made on my first day, huh?"
    "I recall Natsuki proudly presenting her cat-shaped cupcakes, and Sayori and Monika's delighted expressions."
    "I wonder if I can make Natsuki proud like that, too."
    mc "Yeah..."
    mc "Maybe I will use the food coloring, then."
    n "Sounds like you're starting to understand."
    n "Just make sure you completely finish mixing the icing before you mess with the food coloring."
    mc "Yeah, it's getting there."
    "We were using the electric mixer for the batter, so I got stuck with a whisk and a huge bowl for the icing."
    n 4bc "Eh?"
    n "The icing's still all lumpy!"
    n "Are you even trying?"
    mc "Well, yeah..."
    mc "It'll just take a little longer."
    n 4bg "Jeez, I'll be here all night if you do it like that."
    n "Here, look."
    "Natsuki grabs the whisk from me and uses her other hand to tilt the bowl back."
    n 4be "You really need to...beat...the crap out of it!"
    "After a few seconds, the consistency of the icing has already improved."
    n 4ba "See?"
    "As if to emphasize, Natsuki sticks a finger in the icing and pops it in her mouth."
    "I reluctantly start to do the same."
    n 1bh "Hey!"
    "Natsuki suddenly grabs my wrist."
    n 4bh "I don't want {i}your{/i} gross fingers in my icing."
    mc "Your icing, eh?"
    mc "Are you forgetting who did all the work?"
    "I start to fight back, trying to inch my finger toward the bowl."
    n 4by "Don't make me beat the crap out of you next!"
    mc "I'd like to see you try!"
    "I push harder, just enough for my finger to reach the icing."
    "I triumphantly scoop some with my finger just as Natsuki tugs with all her might."
    mc "Ah--!"
    "The force of Natsuki pulling me causes me to stumble, making her stumble in turn."
    n 1bx "恶心！"
    n "你把它弄到我脸上了！"
    mc "那又是谁的错啊？！"
    "夏树的脸颊上有一大团糖霜。"
    n 1bw "嗯——"
    "她试着伸长舌头去舔，但是离得太远了。"
    n 1br "真是的......"
    n "你猜怎么着？"
    n 4bd "吃我这招！"
    "夏树用手指把糖霜拭去，然后猛地朝我脸上一戳。"
    mc "你倒是想得美——！"
    "我的动作更快。"
    "I grab her wrist with my hand before it reaches my face."
    "Natsuki tries to use her other hand to fight back, but I grab that one as well."
    $ persistent.clear[4] = True
    $ renpy.save_persistent()
    scene n_cg3_base
    show n_cg3_exp1
    show n_cg3_cake
    with dissolve_cg
    n "啊哈哈哈！快停下！"
    mc "除非你为说我恶心这件事道歉！"
    n "好吧好吧！"
    n "对不起，我不该说你恶心。"
    n "You know I don't mean it."
    n "It's just fun seeing you react to it."
    n "...You do that to me all the time, you know!"
    n "Saying dumb things just to get a reaction out of me."
    n "You really shouldn't tease girls like that."
    mc "Is that so?"
    mc "In that case, I probably shouldn't do this, either..."
    show n_cg3_cake at cgfade
    hide n_cg3_cake
    "I take Natsuki's finger and put it in my mouth, licking off the icing."
    show n_cg3_exp1 at cgfade
    show n_cg3_exp2 at cgfade
    hide n_cg3_exp1
    n "什、什、什么——？"
    n "D-Did you seriously just--"
    n "啊、啊——"
    "Natsuki is so surprised that she can't even figure out how to get mad at me."
    "Her face is entirely red."
    hide n_cg3_exp2
    n "[player]..."
    n "You really shouldn't do that kind of thing to girls...unless you really like them..."
    n "You know that...right?"
    mc "..."
    "What kind of question is she asking me, just like that?"
    "How did the mood turn to this so quickly?"
    mc "I..."
    "Natsuki gazes at me in silence."
    "I notice her shallow breaths."
    "Why am I starting to feel dizzy...?"
    n "Eh?!"
    scene bg kitchen with dissolve_cg
    "Out of nowhere, the fire alarm starts going off."
    "Natsuki rushes over to the oven."
    mc "Is something burning?"
    mc "I thought you didn't put the cupcakes in yet."
    show natsuki 1bw zorder 2 at t11
    n "{i}*咳咳*{/i}"
    n "No wonder..."
    n 1bb "You left a dirty tray in here, dummy!"
    n "How could you make a mistake like that?"
    mc "You should have checked before turning the oven on!"
    n 1bs "Don't blame me for your mistakes!"
    n "Jeez..."
    "Natsuki uses an oven mitt to grab the blackened tray out of the oven."
    "She sets it on top of the stove."
    "In another moment, the fire alarm stops."
    n 1bq "Anyway..."
    n "I'm...putting them in the oven now."
    mc "Yeah..."
    "The tension from the moment before still lingers over our heads."
    "But the moment has already been lost."
    "I watch as Natsuki slides the cupcake trays into the oven."
    "Then, I reluctantly pick up the whisk and continue with the icing, like nothing ever happened."

    scene bg kitchen
    show natsuki 4bz zorder 2 at t11
    with wipeleft_scene
    n "Ahh, that smells so good!"
    "The cupcakes are ready to be pulled out of the oven."
    "As soon as Natsuki opens the oven door, a blast of sweet-smelling warm air fills the room."
    n 4bl "Look at how cute they all look!"
    "She proudly shows off the different-colored cupcakes in each of the trays."
    mc "They'll look even better once we add the icing."
    n 2ba "Not like you need to tell {i}me{/i} that!"
    n "I brought decorating stuff, so I hope you can get creative."
    n "Here, scoop the icing into these bags."
    "Natsuki hands me some plastic bags."
    n 2bj "I have these nozzles that will make it look nice and fluffy."
    n "This one can even make flowers!"
    n "We probably won't be using it this time, though."
    mc "What's this one for?"
    "I pick up one of the nozzles that has a much thinner tip than the others."
    n 4bk "That one's really thin, so you can use it to make stripes or other patterns."
    n "But you can also use it to write stuff on a cake."
    n "Like, 'happy birthday!' or whatever."
    mc "Huh, I see..."
    mc "That gives me an idea, actually."
    n "Eh?"
    mc "Well, it's a literature event, right?"
    mc "We could make it more literature-themed by writing a different word on each of the cupcakes."
    mc "It would be fun to see people choose their cupcake based on a word they like."
    n 1bq "Uu..."
    mc "Hm?"
    n "I was kind of expecting you to say something really stupid..."
    n 1bs "But that's actually...a really cute idea, so..."
    mc "啊哈哈。"
    mc "Maybe I'm getting it from you."
    n 5bh "W-What's that supposed to mean?"
    n "I'm not cute!"
    mc "Come on..."
    mc "We're not at school, nobody's judging."
    mc "You can't dress and act like this and not expect me to think you're cute."
    n 5bs "W-Well..."
    "Natsuki's voice trails off."
    n "Same with you..."
    mc "Eh?"
    mc "Did you say something?"
    n 1bw "N-No, nothing!"
    n "Let's just do the icing!"
    "Natsuki picks up the pace and fastens a nozzle onto each of the bags."
    n 1bh "There's a lot to do, so we shouldn't be wasting time!"
    n "Here, I'll show you how to do it."
    "Without giving me a chance to think about before, Natsuki quickly moves on."
    "She shows me how to apply the icing, and then we each get to work."

    scene bg kitchen with wipeleft_scene
    "When we're finally finished, Natsuki puts them all side by side to admire our work."
    show natsuki 4bl zorder 2 at t11
    n "Look at how pretty they are together!"
    mc "Yeah, they are, aren't they?"
    n 1bm "Uu... I wish I could have one now!"
    mc "Well, there's no reason you can't, right?"
    mc "I don't see any harm in that."
    n 1bc "Well, yeah, but..."
    n "My dad's making dinner tonight, so I really need to save my appetite."
    mc "啊哈哈。"
    mc "Sayori's the exact opposite in that regard."
    mc "If she was here, we'd probably be down ten cupcakes already."
    mc "And she would still eat dinner."
    n 4bg "Come on, that's just unhealthy!"
    n 4bs "Besides, when my dad cooks, I need to eat as much of it as I can..."
    n 4bq "...Well, anyway!"
    n 4bc "I was hoping we would have time for manga, but I need to be home for dinner..."
    mc "Ah, already?"
    mc "That's a shame."
    n 1bg "It's your fault for working so slowly!"
    n "You should have thought about that."
    n "It's not like you'll always have this chance."
    mc "Man..."
    "As usual, Natsuki places the blame on me."
    n 2bk "You can bring the cupcakes tomorrow, right?"
    n "If you and Sayori each carry some, then you can probably do it in one trip."
    mc "Yeah, I can do that."
    mc "And don't worry, I won't let her eat any."
    n 2ba "啊哈哈。"
    n "I wish she would listen to me the way she listens to you."
    mc "Ah..."
    mc "Yeah."
    show natsuki zorder 1 at thide
    hide natsuki
    "I again think back to the conversation I had with Sayori earlier today."
    "I felt so helpless."
    "Sayori always does listen to me, but at that point it felt like she couldn't listen to me at all."
    show natsuki 4bl zorder 2 at t11
    n "Okay, I'm all packed up."
    n "Good work today!"
    mc "You too."
    mc "I'll walk you out...I guess."

    scene bg house with wipeleft_scene
    "Just like that, Natsuki is already about to leave."
    "It feels like the afternoon went by in a flash."
    "More than that..."
    "Did I even take the opportunity to get closer to her, like I wanted?"
    show natsuki 1bh zorder 2 at t11
    n "Well..."
    n "I guess I'll be off, then..."
    n 1bq "Thanks for all the help and everything..."
    n "I'll see you tomorrow."
    mc "Wait, Natsuki."
    n 1bh "Eh?"
    mc "What you said before...about not always having this chance."
    mc "It doesn't have to be that way at all!"
    mc "I had fun today."
    mc "You showed me how fun baking can be, like you wanted."
    mc "But aside from that..."
    mc "You can come over anytime, okay?"
    mc "I think that if possible, I'd like to spend more time like this."
    mc "If you want to read manga, or go out somewhere--"
    n 1bm "Um--"
    n "Do you...really mean that?"
    "Natsuki looks at me tensely, like she's trying to hide her expression."
    mc "Yeah."
    mc "I want to spend more time with you."
    n 1bq "[player]..."
    n "I thought you only cared about getting this done..."
    n 1br "Uu..."
    n 1bn "I'm sorry I had to leave so early today."
    n "I really didn't want to!"
    n "I would really...stay here longer if I could."
    n "I feel the same way as you, so..."
    stop music fadeout 2.0
    show natsuki 1bi at face with dissolve
    "Natsuki suddenly gets closer to me."
    mc "Wait, Natsuki--"
    "Standing inches from me, Natsuki looks up at me."
    "I feel her fingers gently clutch at the sides of my shirt, as if holding onto me."
    "Her rose-colored cheeks and matching eyes fill my vision, along with her slightly-parted lips."
    "What is happening...?"
    "My head starts to go dizzy as I feel her soft breaths against me."
    n 1bh "I've felt it..."
    n "For a while now..."
    n 1bo "——！！"
    show natsuki zorder 2 at t11
    "夏树突然往后一跳。"
    n "纱、纱世里？！"
    mc "诶？！"
    show natsuki zorder 2 at t22
    show sayori 1bl zorder 3 at f21
    s "啊......"
    s "嗨、嗨，[player]......"
    mc "纱世里——！"
    mc "我们刚刚不是在——"
    s 1bq "欸嘿嘿~"
    s "没关系的，[player]。"
    s 1ba "我只是顺路过来打个招呼~"
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 5bq "A-Ah..."
    n "Well..."
    n 5bw "Y-You should have come a little earlier!"
    n "I'm already on my way out, so..."
    show natsuki zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "呀，真的吗？"
    s "那太可惜了......"
    show sayori zorder 2 at t21
    show natsuki zorder 3 at f22
    n 2bq "嗯，这个嘛......"
    n "明天还能在学园祭上见面，所以也没关系的。"
    n 2bb "不过记得不要在学园祭前偷吃蛋糕哦！"
    n "那么，回见！"
    show natsuki at lhide
    hide natsuki
    "夏树慌慌张张地仓促离开了，而纱世里还在那里挥手告别。"
    return

label ch4_exclusive_yuri:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "快到家时，眼前的一幕让我感到好一阵慌乱。"
    mc "优里——？"
    show yuri 2bq zorder 2 at t11
    y "啊......"
    y "谢天谢地......"
    mc "You're a little early..."
    mc "抱歉我刚刚不在家！"
    mc "Were you waiting for a long time?"
    y 1bf "No, I just got here."
    y 1bh "But I started to get really nervous when nobody answered the doorbell..."
    mc "You always could have texted me."
    mc "If I had known, I would have reassured you and hurried more on my way home."
    y 2bv "Ah...I suppose that's true..."
    y "I didn't think of that...for some reason."
    "It should be common sense to do that, but I decide to ignore it."
    mc "Anyway...let's go inside."
    mc "I see you brought a lot of stuff with you."
    y 1ba "That's right."
    y "And did you manage to find everything I asked you to buy as well?"
    mc "Yeah, pretty much."
    mc "At least, I hope I got everything right."
    y "I'm sure it will be fine."
    scene bg bedroom with wipeleft
    "I take Yuri to my room."
    "The first thing she does is glance around curiously, which makes me feel anxious."
    show yuri 2bm zorder 2 at t11
    y "It's so clean..."
    mc "啊哈哈......"
    mc "I cleaned it before you came over, so..."
    y 2ba "That's very considerate of you to do."
    mc "Ah, no..."
    mc "I would be really embarrassed for my room to be a mess while you were here."
    y 1ba "Hmm..."
    y "Well, I do enjoy cleaning..."
    y "I would have gladly helped you clean."
    mc "Ah--"
    mc "That would be even more embarrassing!"
    show yuri 1be
    mc "Wait, don't look in there--!"
    "I snatch Yuri's wrist, which was in the process of opening a desk drawer of mine."
    y 3bn "A-Ah..."
    y "I'm sorry...!"
    y 4bb "I wasn't thinking for some reason..."
    y "I was just spacing out!"
    mc "It's fine, it's fine..."
    "I let go of Yuri's wrist."
    show yuri 1bl
    "She puts both of her hands firmly in her lap, as if making sure she's keeping track of them."
    mc "So, um..."
    mc "Should we...get started?"
    y 2bu "Ah..."
    y "Yes..."
    y 2bf "Um, I have a few things planned that you can help with..."
    y "Decorations and other atmospheric enhancements."
    mc "Atmospheric enhancements...?"
    y 1ba "You know..."
    y "Mood lighting, aromatherapy candles..."
    mc "Oh, wow."
    mc "I didn't know you planned on taking it that far."
    y 1bc "Of course."
    y "I want to help take our guests to a faraway place."
    y 1ba "Although many will stop by just out of curiosity..."
    y 1bj "And for...cupcakes, I guess..."
    y 1ba "I'm determined to provide an experience that will leave them wanting more."
    mc "That's great."
    mc "It's easy to forget that you're a pretty intense person."
    y 1bt "Ah--"
    y 2bt "Intense...?"
    mc "I guess that's the best way to put it."
    y "Is that...a bad thing?"
    mc "No, not at all."
    mc "It's something that I like about you, actually."
    y 3bu "I-Is that so...?"
    y "That makes me feel relieved..."
    y "And kind of happy..."
    mc "Yeah, no need to be so anxious."
    mc "You can relax a little."
    y 3bl "Relax..."
    y 1bf "I brought some things for relaxation."
    y "I was going to use them during the poetry event..."
    mc "Oh yeah? Like what?"
    y "Let's see..."
    "Yuri rummages through her bag."
    "She pulls out a few candles and a wooden cylinder-shaped object."
    y "I did some shopping on the way here, so I happen to have these in my bag."
    y "I planned to cover the windows in black paper and use the candles to light the room."
    y 1ba "I think that would be amazing, don't you?"
    mc "Yeah, that would be really neat."
    mc "What's that wooden thing, though?"
    y 1bf "Oh, this?"
    y "It's a diffuser for essential oils."
    y "How familiar are you with aromatherapy?"
    mc "Not familiar at all..."
    y 1ba "Ah, is that so?"
    y "It's one of my favorite contributors to a positive atmosphere."
    y "Depending on the oils or herbs you choose, you can change the mood of the air itself."
    y "You can even feel it permeate through your body."
    y 3bm "Relaxation, positive energy, romance, reflection..."
    y "It's almost like magic."
    show yuri 3ba
    "Yuri takes the cylinder and pushes a switch on the bottom."
    "In just a moment, a thin ray of vapor begins to spout through a small hole on the top."
    mc "Wow, that smells wonderful."
    mc "What kind of mood is that one for?"
    y 1ba "This is a Jasmine essential oil."
    y "It smells a little sweet and flowery, right?"
    mc "Yeah, that's a good way to describe it."
    y 1bb "I chose Jasmine for the event because it provides more than relaxation."
    y "Jasmine enhances your emotions and helps you feel them flow through your body."
    y 1bu "You feel warmer, and your heart pounds more heavily."
    y 1ba "Don't you think that will be perfect for sharing our poems?"
    mc "It does sound suitable..."
    mc "But you seem to know a lot about this, so I'll trust your opinion with anything."
    show yuri 1bc
    "Yuri smiles gently, clearly enjoying herself."
    "She again reaches into her bag and pulls out several spools of thin ribbon."
    show yuri 1ba
    mc "What are those for?"
    y 1bf "Well..."
    y "Did you purchase the origami paper I asked you to get?"
    mc "Yeah, I have it over here..."
    y "We won't be using the paper for folding origami."
    y "What I'd like to do is write a different word on each paper."
    y "We'll need about a hundred of them."
    mc "Oh yeah?"
    mc "What will those be used for?"
    y 2bf "Well, I'm going to cut pieces of ribbon to hang from the doorway of the classroom."
    y "Then, we can fasten the paper onto the ribbons to create a doorway curtain."
    y 2bm "Wouldn't that be beautiful?"
    y "It would also catch the eye of those passing by the room..."
    y 2ba "It may attract some to peek inside."
    mc "That's really creative!"
    mc "I had no idea you'd be so good at this, Yuri."
    y 4ba "Is...that so?"
    y "Well, I suppose I do get a little intense...as you'd put it."
    y 3bu "Uhuhu."
    "Yuri giggles with red cheeks."
    "Is it just me, or is she more relaxed when it's just the two of us?"
    "Or maybe it's the excitement she feels from sharing something that she enjoys."
    y 1ba "Here's a marker, [player]."
    y "You can write any characters you want."
    y "I'll help you once I finish cutting the ribbons."
    mc "Ah, alright."
    "Sitting on the floor together, the two of us get to work."
    "I carefully draw a different character on each paper, doing my best to manage my bad handwriting."
    "Yuri unravels a long strand of red ribbon to her desired length."
    "Then, she reaches into her bag once more and pulls out a pocket knife."
    mc "Eh...?"
    "The knife is strangely beautiful."
    "The silver handle has an intricate pattern of waves etched into it."
    "The blade itself is gently tinted blue."
    mc "That's no ordinary pocket knife..."
    mc "It looks really fancy."
    y 4bb "啊、啊......"
    y "Well..."
    "Embarrassed, Yuri looks away."
    mc "What is it?"
    y "You're going to think it's weird..."
    mc "Yuri, whatever it is, I have no reason to judge."
    mc "To each their own, you know?"
    y "If you promise you won't be weirded out..."
    mc "Yeah, I promise."
    y 2bi "Alright..."
    y "The thing is, I'm kind of into knives..."
    y "They're just...so pretty..."
    y 2bv "I-I can't help it!"
    y "I don't know what it is..."
    y "The combination of craftsmanship and feeling of danger, maybe..."
    y 4bb "Uu, what am I saying...?"
    y "Please don't think I'm weird for this..."
    mc "啊哈哈。"
    y "You're laughing at me..."
    mc "No, I'm not laughing at you."
    mc "It's just funny how nervous you got about sharing."
    mc "It's...well, it's an interesting thing to be into, I guess."
    mc "But I think it kind of suits you."
    y 2bt "Suits me...?"
    mc "Yeah... It's kind of intense. Ahaha."
    mc "Besides, it's a really cool-looking knife, I can't deny that."
    y 2bu "It is, isn't it...?"
    "Yuri relaxes her expression once again."
    y 1ba "Would you like to hold it?"
    mc "Sure, I'll check it out."
    "Yuri carefully hands me the knife, with the handle facing me."
    "I take it and turn it around in my hands."
    "It feels heavy, and extremely solid."
    "Where do you even get a knife like this...?"
    "Curious of its sharpness, I feel the point of the knife with my index finger."
    mc "Ow--!"
    y 3bn "[player]--!!"
    y "Why did you do that?!"
    mc "I didn't expect it to be that sharp...!"
    mc "I barely touched it at all."
    y "I-It's my fault!"
    y 3bo "I should have warned you..."
    y "This knife is extremely sharp..."
    y "It can cut through skin like it's paper."
    y 2bv "Oh no..."
    "A small drop of blood trickles down the side of my finger."
    "Yuri takes my hand and gives the wound a closer look."
    y 2bt "Ah..."
    "She stares at it and noticeably fidgets."
    mc "If you're squeamish, I'll go wash it off now--"
    mc "A-Ah!"
    "Without warning, Yuri puts my finger in her mouth and licks the wound."
    "I feel her tongue curl around my finger."
    "Startled, I instinctively pull my hand back."
    y "O-Oh..."
    y 3bo "P-Please forgive me!"
    y "I wasn't thinking!"
    y 4bc "I..."
    "Yuri lowers her head, her face burning up."
    mc "Yuri..."
    y "That's the most embarrassing thing I've ever done..."
    y "How could I do something like that??"
    y "I'm sorry, I'm sorry..."
    mc "Ah..."
    "Sure, it was a little weird, and it took me by surprise..."
    "But I guess she was just trying to help, right...?"
    mc "Yuri, I think you're overreacting a little..."
    y "Uuuh..."
    "She doesn't lift her head."
    "What if she doesn't recover from this for the rest of the afternoon?"
    mc "Alright, you know what..."
    "This might be a stupid thing to do, but I do it anyway."
    "I take Yuri's hand and lick her index finger in return."
    show yuri 3bn at h11
    y "[player]——！！"
    y "D-Did you really just do that?"
    mc "N-Now we're even..."
    y 3bv "..."
    "Yuri just looks at me like I did something wrong."
    mc "啊哈哈......"
    mc "I knew that would be a bad idea..."
    "If not for the sweet aroma of the Jasmine oil, the air would be extremely heavy right now."
    y 1bu "You're so weird, [player]."
    "Yuri giggles shyly."
    mc "Eh...?"
    "Yuri calling {i}me{/i} weird?"
    "I have no response to that..."
    y 1bf "Where do you keep your bandages?"
    mc "Ah..."
    mc "I don't think I need one, actually."
    mc "It was a tiny cut."
    mc "Look, it already stopped bleeding."
    y 1ba "I see..."
    y "That's relieving."
    "The tension is quickly lifted."
    "We each resume our respective activities."
    "I watch Yuri's knife cut through the ribbon like it's nothing but air."
    "Meanwhile, I continue to make progress on the paper."

    scene bg bedroom with wipeleft_scene
    "After we finish attaching the paper to the ribbons, we lay them all out side by side."
    "It looks better than I expected and will be very effective as a door curtain."
    mc "It looks great."
    mc "Good thinking coming up with this, Yuri."
    show yuri 1bq zorder 2 at t11
    y "Ah, thanks..."
    y "It's just something I saw online, really."
    y 1ba "Are you ready to move onto the next task?"
    mc "Yeah, let's do it."
    mc "What do you have in mind?"
    y "I'd like to create a banner."
    y "That's why I asked you to buy the paint tablets."
    mc "Ah, that's right."
    "One of the items Yuri had asked me to buy was a kit of watercolor paint tablets."
    y 1bf "We'll need about six cups of water to put each of the tablets in."
    y "Do you mind fetching those for us?"
    mc "Of course not."
    mc "Six cups of water..."
    mc "I'll be right back in a minute."
    y 1ba "Thank you very much."
    y 2bf "Oh, and just a little bit of water is okay."
    y "If you fill the cups too much, it will be too diluted."

    scene bg bedroom with wipeleft_scene
    "Taking Yuri's advice, I decide to use small plastic bathroom cups rather than full-sized glasses."
    "I put them on a plate to catch any paint that drips, then bring it back into my room."
    mc "Yuri?"
    show yuri 1bd zorder 2 at t11
    y "Yes?"
    "I come in to see Yuri quickly unrolling her sleeve, pulling it back over her arm."
    mc "Ah, nothing..."
    mc "Your face is a little red."
    mc "Is it too hot in here, or anything?"
    y 3bq "Ah--"
    y "No, not at all!"
    y "There's nothing wrong, so..."
    y "Let's mix the paint."
    "Yuri hurriedly dismisses me and takes it upon herself to unwrap the tablets, dropping them into the cups."
    y 1ba "So..."
    y "I thought we would do something simple that would look very nice."
    y "I'd like to paint a gradient across the banner..."
    y "Starting with the colors for a sunrise, then daytime, then sunset and nighttime."
    y "Once it dries, I'll write an inspirational quote across the banner."
    y "We can hang it on the wall behind the podium at the front of the classroom."
    mc "Ah, neat."
    mc "What are you going to write?"
    y 2bm "Well..."
    y "...It will be more fun to surprise you."
    "Yuri smiles at me."
    mc "If you say so..."
    show yuri zorder 1 at thide
    hide yuri
    "After rolling out the banner, Yuri and I kneel on opposite sides so we don't get in the way of each other."
    "Yuri uses a brush and adds a few dots of different colors across the banner to serve as a color guide when we paint."
    mc "This kind of reminds me of elementary school..."
    "Painting on a banner with watercolors feels a lot like the art class projects we had back then."
    "It's relaxing."
    show yuri 2bt zorder 2 at t11
    y "啊......"
    y "I'm sorry if this feels too childish...!"
    mc "No, I didn't mean that at all."
    mc "It's kind of fun, you know?"
    y 1bs "...Yeah."
    y "It is fun."
    y "I'm glad you feel that way, too."
    "Yuri stops painting for a moment, thinking to herself."
    y 2bl "For me..."
    y "I don't need to go out and do crazy things to have fun."
    y "In fact, I usually don't even want to."
    y 2bf "I just like when I can spend time with one other person..."
    y "Even if it's something simple, like reading - it doesn't even matter if we don't talk much."
    y 2ba "Just having a friend next to me makes things feel a little bit nicer."
    y "I think that's all it takes for me to be happy."
    mc "Is that so...?"
    "Even if Yuri and I are quite different, I can understand where she's coming from."
    "I feel that way about things like anime and games, where simply sharing the experience with someone can make me happy."
    mc "I think I feel the same way."
    "Yuri smiles gently."
    y 1bm "I knew you'd understand..."
    "Yuri leans over the banner to grab an unused paintbrush."
    "But I move at the same time, causing my head to bump into hers."
    y 3bn "Kya--!"
    mc "S-Sorry!"
    "Yuri reels back, and I quickly lift my hands in surprise."
    mc "Are you hurt?"
    y 2bv "N-No, I'm not hurt."
    y "It just startled me...that's all."
    y "Sorry, I should have asked you to get it for me..."
    mc "It's not your fault."
    mc "Ah, your face..."
    "There are droplets of paint on Yuri's face and neck."
    y 2bt "Is there something on my face?"
    mc "Yeah, I accidentally got paint on you..."
    mc "Sorry, it's totally my fault!"
    mc "I'll get a towel right away."
    show yuri zorder 1 at thide
    hide yuri
    "I rush out and fetch a small towel, then I dampen it with hot water."
    "I return to my room and kneel back down in front of her."
    $ persistent.clear[5] = True
    $ renpy.save_persistent()
    scene y_cg3_base with dissolve_cg
    mc "Here..."
    "I pat down Yuri's face and neck with the towel."
    show y_cg3_exp1 at cgfade
    y "Ah--"
    mc "Is something wrong?"
    y "It's hot...I just didn't expect it."
    mc "Sorry..."
    mc "I didn't want to use cold water."
    "Having finished, I start to retract my hand."
    "But Yuri suddenly holds my wrist."
    hide y_cg3_exp1
    y "Wait--"
    mc "Eh?"
    show y_cg3_exp1 at cgfade
    y "Just...for a little longer."
    y "It feels really nice..."
    mc "Ah..."
    "I keep my hand still against Yuri's neck."
    hide y_cg3_exp1
    "She looks into my eyes."
    "It's an intense expression that I recognize from when she reads her books..."
    "Almost as if she's lost in a daze, enveloped by her own thoughts."
    "She breathes gently, half through slightly-parted lips."
    "What is happening...?"
    "Is it the aroma of the Jasmine oil giving me this dizzy feeling?"
    "Yuri's gentle fingers, wrapped around my wrist, send a tingling sensation through my arm."
    "And suddenly, her face seems to be much closer to mine than it was just a moment ago..."
    y "Ah..."
    "Yuri slowly pulls away."
    y "抱歉......"
    y "I've been feeling a little light-headed today."
    y "I didn't mean to space out..."
    mc "I-It's fine..."
    scene bedroom with dissolve_cg
    "The moment is over as soon as it began."
    "Yuri picks up her brush again."
    "But her movements seem clumsier, like she's unable to focus."
    "I remain silent, forced to ignore the event that just transpired."
    "I hesitantly retrieve my own brush and continue following Yuri's example."

    scene bedroom with wipeleft_scene
    mc "That should do it..."
    "I finish filling the night sky with white dots that look like stars."
    "Looking at the banner as a whole, it's very pretty and natural-looking."
    show yuri 1ba zorder 2 at t11
    y "I think it came out better than I expected."
    y "I'm really happy with the results."
    mc "Yeah, me too."
    mc "Are you going to add the lettering now?"
    y 1bf "Ah, not yet..."
    y "It needs to dry first."
    mc "That's true, but won't that take a while?"
    y 2bh "Well..."
    y "Perhaps it would be best to leave it here, then have you bring it in the morning."
    y 2bf "I can do the lettering in the classroom before our event starts."
    y "Is that okay?"
    mc "That's totally fine."
    y 1ba "Wonderful."
    y "In that case..."
    y "I don't think there's anything more for us to do here."
    mc "Phew."
    y 1bc "啊哈哈。"
    y "You say that like you're glad it's over."
    y 1ba "Was I wrong to assume that you were at least enjoying yourself a little bit?"
    mc "Ah, no, it's not that."
    mc "I'm just glad that we managed to get everything done."
    y 2ba "I see."
    y "I am, too."
    y "I was a little concerned about time..."
    y "I need to start making dinner soon."
    mc "Ah..."
    mc "So you don't have any time left?"
    "I was secretly hoping we would have extra time after finishing the work..."
    y 2bl "Well..."
    y "..."
    "Yuri thinks to herself."
    y 3bv "I-I think it would be too irresponsible of me to wait much longer..."
    y "I'm sorry!"
    y "I was hoping there would be more time as well..."
    mc "It's probably my fault."
    mc "Sorry for being such a slow worker."
    y 1bt "No, it's not your fault at all."
    y "And...the important thing is that we got everything done, right?"
    mc "Yeah..."
    y 1bu "So..."
    y "I shouldn't be disappointed...or anything."
    "Gathering all her things, Yuri seems to look a little downcast."
    "I understand why."
    "It sounded like she rarely gets the opportunity to spend time with friends in a relaxed environment."
    "But that doesn't mean this is the last time it can happen..."

    scene bg house with wipeleft_scene
    "Once Yuri packs up, I walk her out the front door."
    show yuri 1ba zorder 2 at t11
    y "Thank you very much for having me today."
    mc "No problem, I'm glad I was able to help."
    mc "Just let me know if there's anything else you need me to bring tomorrow."
    y "I will."
    y 1bu "Well, then..."
    "Yuri fidgets."
    y 2bu "I guess...I'll see you tomorrow."
    mc "Wait--"
    show yuri 2bt
    "I kind of say that without thinking."
    mc "About today..."
    mc "It's fine that we didn't have as much time as we wanted."
    mc "Because we can do this again."
    mc "Whenever you want, you can come over, or we can go out somewhere--"
    mc "Ah, I forgot you don't like going out much--"
    show yuri 2bs
    "As I stumble over my words, Yuri simply smiles bashfully."
    mc "Anyway..."
    mc "You know what I'm trying to say, so..."
    y 1bs "You're very thoughtful, [player]."
    "Yuri takes a step closer to me, then briefly squeezes my hand."
    show yuri 2bs at face(y=600) with dissolve
    stop music fadeout 2.0
    y "I kind of like that about you..."
    mc "这个嘛......"
    "这要我怎么回应啊？"
    "不过还没等我回应，优里就突然抽身退了回去。"
    show yuri 3bn zorder 2 at t11
    y "纱、纱世里——？"
    mc "诶？！"
    show sayori 1bl zorder 3 at f21
    show yuri zorder 2 at t22
    s "啊......"
    s "嗨、嗨，[player]......"
    mc "纱世里——！"
    mc "我们刚刚不是在——"
    s 1bq "欸嘿嘿~"
    s "没关系的，[player]。"
    s 1ba "我只是顺路过来打个招呼~"
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 3bq "U-Um..."
    y "Well, it's nice to see you..."
    y 3bv "I'm sorry, but I'm already on my way to leave!"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 1bh "呀，真的吗？"
    s "那太可惜了......"
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 2bt "抱歉......"
    y "不过明天大家都会去学园祭的，所以......"
    y "所以也没关系的，对吧？"
    show yuri zorder 2 at t22
    show sayori zorder 3 at f21
    s 4bq "那当然！"
    "纱世里笑容满面地说道。"
    show sayori 4ba
    show sayori zorder 2 at t21
    show yuri zorder 3 at f22
    y 4bc "是、是啊，那......"
    y "那明天再见！"
    show yuri at lhide
    hide yuri
    "优里显然有些尴尬，匆匆忙忙地走了。"
    "纱世里还在她身后挥手告别。"
    return



label ch4_end:
    play music t10 fadeout 2.0
    show sayori 1ba zorder 2 at t11
    mc "纱世里——"
    mc "我还以为你今天不想过来呢！"
    s 2bl "啊哈哈，好吧......"
    s "我试着呆在房间里......"
    s "但是我的妄想一直折磨着我......"
    s 1by "所以我只好过来亲自看看。"
    mc "看什么啊？"
    mc "你到底在说些什么呀？"
    s "就是......"
    s "来看看你和[ch4_name]玩得有多开心。"
    s "还有你跟她变得有多亲密。"
    s 1bt "我......很高兴......"
    s "你们已经变成了这么好的朋友。"
    s "这对我来说才是最重要的。"
    "泪水开始从纱世里的脸上流下了。"
    s 4bv "这对我来说才是最重要的——！"
    s "[player]，为什么我会有这种感觉？"
    s "我本该为你高兴。"
    s 4bw "为什么我的心却感觉仿佛撕成了两半？"
    s "好疼啊......"
    s "这一切都好疼啊......"
    s "要是我能干脆消失的话，一切都会好很多！"
    mc "纱世里，别那么说！"
    s 1bw "这是事实，[player]！"
    s "要是我不在这个世上，你也就不需要在我的身上浪费你的同情心了！"
    s "你就不需要忍受我的自私！"
    s 1bv "莫妮卡说得没错......"
    s "我就应该直接......"
    mc "莫妮卡......？"
    mc "莫妮卡说的什么没错？"
    s "......"
    mc "纱世里......"
    mc "我之前说的话绝无半句谎言。"
    mc "我不会让你继续像这样痛苦下去的。"
    mc "我对你的关心并不像你想的那样，是一种累赘什么的。"
    mc "对我而言，这不是累赘，而是能让我快乐的事情，"
    mc "是我不会用任何东西来交换的事情。"
    mc "所以，即便必须花上一辈子......"
    mc "我也会一直陪在你身边，直到你再也感受不到痛苦为止。"
    s 1bk "但、但是......"
    "紗世里掉转了目光。"
    "我把手放到她的肩膀上，让她放心。"
    s "我好害怕，[player]......"
    s "我真的很害怕......"
    mc "你在害怕什么，纱世里？"
    s "我害怕......"
    s "比起你喜欢我，我更喜欢你......"
    mc "纱世里......？"
    s 1bu "这是事实，对吧？"
    s "我很软弱，所以就开始过分喜欢你......"
    s "一切都是我作茧自缚。"
    s "[player]......"
    s 4bw "我好喜欢你，喜欢到想要去死！"
    s "这就是我的感受！"
    s 2bv "还有......还有......"
    mc "够了，纱世里......"
    mc "我不想再让你受伤了。"
    "我的手沿着纱世里的手臂往下滑，轻轻地将她的手捏在自己掌中。"
    mc "你还记得我是怎么说的吗，我总是知道什么对你来说才是最好的？"
    mc "你还相信我吗？"
    "纱世里默默地点了点头。"
    mc "即便你不能理解自己的所有情感......"
    mc "我也知道你现在最需要的是什么。"
    mc "而这就是我会给你的答案。"
    show black zorder 4 with dissolve_cg

    menu:
        mc "纱世里......"
        "我爱你。":

            $ sayori_confess = True
            hide black with dissolve_cg
            call ch4_end_yes
        "你永远是我最亲爱的朋友。":
            $ sayori_confess = False
            hide black with dissolve_cg
            call ch4_end_no

    return

label ch4_end_yes:
    mc "我爱你。"
    s 1bv "诶——？"
    mc "这是我的真实感受。"
    mc "所以......你喜欢我的程度，不可能比我喜欢你的程度还多。"
    mc "我真该早点发现的。"
    mc "但是在社团里和大家一起度过的时光......"
    mc "交新朋友......"
    mc "以及每天都和你一起快快乐乐的......"
    mc "这些都让我明白，你才是我最重要的人。"
    mc "这就是为什么我会接受你所背负的一切。"
    mc "只要我们每天像这样继续下去......"
    mc "有你好好陪在我身边......"
    mc "那我们一定都会快快乐乐的。"
    s "[player]......"
    $ persistent.clear[8] = True
    $ renpy.save_persistent()
    scene s_cg3 with dissolve_cg
    "突然之间，纱世里紧紧地抱住了我。"
    s "[player]......"
    s "这样......真的可以吗？"
    mc "嗯。"
    "我把纱世里抱在怀里，又把她抱得更紧了一些。"
    mc "你再也不用放手让我离开了。"
    s "[player]，我爱你......"
    s "我想和你永远在一起。"
    mc "我也是。"
    s "......"
    "我感觉到纱世里抱着我的力量减弱了一些。"
    s "这是怎么回事......？"
    mc "纱世里......？"
    s "我现在应该感到开心啊......"
    s "我一直以为这应该是我最开心的时刻。"
    s "但是为什么啊......？"
    s "即便是现在这种时候......"
    s "为什么乌云还是没有消散啊？"
    s "它们一点也没有消散啊，[player]......"
    mc "没关系的，纱世里......"
    mc "也许要花上一些时间，才能让一切再次好转。"
    mc "不过不管要花多少时间，我都会一路陪着你。"
    mc "这才是当下最重要的事情。"
    s "好、好吧......"
    s "我......相信你......"
    scene bg house
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "纱世里和我慢慢地松开了对方。"
    mc "那么......"
    mc "这样一来，明天的学园祭就是......我们的第一次约会了，是吗？"
    s 1by "欸嘿嘿......"
    s "你在说什么啊？"
    s "我不想去考虑那样的事情，好吗？"
    s "我希望一切都和平常一样。"
    s "即便我们真的......成为了恋人。"
    s 1bk "我不知道自己现在还能不能承受得了更多的事情了......"
    s "对我来说，这一切非常新鲜，但又很可怕。"
    mc "我能理解。"
    mc "我们就按照最适合你的节奏来吧。"
    s 1bd "嘿，[player]......"
    "纱世里又一次看着我，悲伤地微笑着。"
    s 4bd "就算我变得非常、非常伤心......"
    s "这对我来说也是最好的安排......是吗？"
    mc "诶......？"
    "我不是很能理解纱世里说这句话的含义。"
    mc "你是说刚刚发生的一切让你觉得伤心了吗，纱世里？"
    s 4bk "我、我不知道......"
    s "我无法理解自己现在的感受。"
    s "你说你爱我的时候，感觉像是一丛荆棘一样......"
    s 4bd "不过这也是为什么我想要相信你。"
    s "因为，你知道怎么做对我来说才是最好的......"
    mc "......嗯。"
    mc "我知道的。"
    mc "这是我的承诺。"
    show sayori zorder 1 at thide
    hide sayori
    "我嘴上是这么说的，但老实说，纱世里从未像现在这样让我捉摸不透。"
    "我知道我爱她，她也爱我。"
    "但是我也和纱世里一样，没法理解她的感受到底从何而来。"
    "即便我可以安慰她......"
    "我不停想着，我是不是应该做得更多一点，又或者换个别的办法。"
    "我知道在一切回归正轨之前，这些想法还会继续困扰着我。"
    "纱世里之前说不想要任何事物改变，就是这个意思吗？"
    "我不知道。"
    "但是我知道我愿意付出一切。"
    "纱世里是对我最重要的人。"
    "只要能和她有个开心幸福的未来，我什么都愿意做。"
    return


label ch4_end_no:
    mc "你永远是我最亲爱的朋友。"
    mc "你最需要做的，就是让一切保持原样。"
    mc "莫妮卡把实情都跟我说了......"
    mc "她告诉我，你在我加入社团后变得开心了许多。"
    mc "我知道你现在正在和你的负面情绪艰难搏斗。"
    mc "不过......"
    mc "请相信我，我知道对你来说，怎么做才是最好的......该做什么才能让你变得快乐起来。"
    mc "我保证我会让一切都重回正轨。"
    s 1bt "我......"
    s "我......知道了......"
    "纱世里在无比痛苦的表情之中挤出一个微笑。"
    s "啊哈哈......"
    s "胸口被扎了一刀......原来就是这样的感觉吗？"
    s "我真应该为此写一首诗......"
    mc "纱世里——"
    s "没关系的。"
    s "这只不过是我的惩罚......记得吗？"
    s "只不过是在惩罚我的自私......"
    s "所以请你......"
    s "请你不要为这些愚蠢的情感而担心。"
    s "我知道你是对的。"
    s "我一直都知道这样下去是不会有快乐的。"
    s "这就是为什么我会来这里......"
    s "我只是为了得到我需要亲耳听到的答案。"
    s "还有另一件事......"
    s "你说得没错，我只是想让一切重回正轨。"
    s "我现在意识到了。"
    s "[player]，你确实比任何人都要了解我。"
    s 4bv "我什么都相信你......"
    s "任何事情都可以......"
    s "所以......"
    show sayori zorder 1 at thide
    hide sayori
    "纱世里的微笑终于撑不住了。"
    "突然之间，她转身跪倒在地上。"
    s "{i}呜啊啊啊啊啊啊啊啊啊啊——————！！！！{/i}"
    "她双手捂住头，用尽全身力气，大声地尖叫起来。"
    "我被震惊到不知该作何反应。"
    show sayori 4bt zorder 2 at t11
    s "......"
    show sayori at lhide
    hide sayori
    "纱世里扭过头，迅速向我抛出一个更加虚弱的微笑，然后就转身跑了。"
    mc "纱世里！"
    "......"
    "我无助地站在家门口。"
    "为什么我对此感到无比难受？"
    "我什么都做不了。"
    "我能做的最多就是支持纱世里克服她的感受，帮助她重回正轨。"
    "但是我也和纱世里一样，没法理解她的感受到底从何而来。"
    "即便我可以安慰她......"
    "我不停想着，我是不是应该做得更多一点，又或者换个别的办法。"
    "我知道在一切回归正轨之前，这些想法还会继续困扰着我。"
    "我会尽我所能的。"
    "纱世里永远是我最亲爱的朋友。"
    "只要能让她每天绽放微笑，我什么都愿意做。"

    return

